### ISSUE TITLE
No Universal binary for M1 Mac

### ISSUE THREAD

**Issue by sodul** [mozilla/sops#1000]
Apple has deprecated Intel for ARM based CPUs. The binary releases only include support for Intel. While they still work for now through Rosetta the new releases should either provide universal binaries for darwin or distinguish between amd64 and arm64.

**Comment by jhelbling** [comment]
https://formulae.brew.sh/formula/sops 

Use brew

**Comment by sodul** [comment]
@jhelbling  Thanks to your tip I realized I could try `go install` and it worked perfectly on macOS Intel and ARM:
```
> go install go.mozilla.org/sops/v3/cmd/sops@v3.7.1
go: downloading github.com/google/shlex v0.0.0-20181106134648-c34317bd91bf
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading gopkg.in/ini.v1 v1.44.0
go: downloading github.com/google/go-cmp v0.5.0
> ~/go/bin/sops --version                          
sops 3.7.1 (latest)
```

We use go 1.17 so this is actually very simple and efficient without having to deal with brew drawbacks.

We want to avoid brew as much as possible since we want to have a very consistent toolchain across our engineers and we ran in a lot of issues where different internal users ended up with very different versions of tools and libraries, which ended up causing a lot of grief for us in the past.

**Comment by ajvb** [comment]
This has been fixed in the newest release: https://github.com/mozilla/sops/releases/tag/v3.7.2
