### ISSUE TITLE
Abandonware status?

### ISSUE THREAD

**Issue by sodul** [mozilla/sops#1010]
It looks like the project is left unmaintained since April 2021 while it used to get several updates per month before that.

We are starting to investigate alternatives, but getting some input from the current maintainers on the future of SOPS would help us prioritize that research.

Thank you!

**Comment by stuart-warren** [comment]
the [develop](https://github.com/mozilla/sops/tree/develop) branch does have slightly newer work on

**Comment by felixfontein** [comment]
Did you see https://github.com/mozilla/sops/discussions/927#discussioncomment-2183834 (and the whole discussion in there)?

**Comment by ikedam** [comment]
Why I was mentioned? @stuart-warren

**Comment by stuart-warren** [comment]
You were a recent committer to the branch and thought you might know the status of the project.

felixfontein has helpfully linked to a recently updated issue though. thank you 👍

**Comment by felixfontein** [comment]
Please note that neither @ikedam nor me have commit rights in this project. Our commits were merged (from PRs) by maintainers, and we have no control at all over this project. If you look at the PRs that resulted in the commits you can see that we did not merge them.

**Comment by ajvb** [comment]
As stated, this has been addressed here: https://github.com/mozilla/sops/discussions/927#discussioncomment-2183834

We'll have more updates soon.

I'll leave this open for a few days in case anyone wants to drop in any questions. Also, feel free to email me at my Github username at `mozilla.com` any sops related questions.
