### ISSUE TITLE
Authenticate aws-cli at runtime instead of aws default profile (during decryption)

### ISSUE THREAD

**Issue by jzavgok** [mozilla/sops#1017]
Hi
I am trying to integrate sops on our build servers, problem i am having is that our servers do not have .aws configured, there are no aws profiles preconfigured.
We orchestrating our processes via Jenkins, and we store our auth to aws and so on in Jenkins credentials store. These credentials are used at run time as command line arguments.

Is it possible to pass in something along the lines of:
`sops -d --aws_access_key_id ***** --aws_secret_access_key  *****` 

So these values would overwrite credentials from default profile (if exists)

Alternatively if these values could be added to env, that would work too.

**Comment by bartmanus** [comment]
Hey, you can [set env vars](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) to set up credentials. sops will use them just like AWS CLI would:
```bash
export AWS_ACCESS_KEY_ID='' AWS_SECRET_ACCESS_KEY='' AWS_DEFAULT_REGION=us-east-1
sops -d
```

**Comment by jzavgok** [comment]
> Hey, you can [set env vars](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) to set up credentials. sops will use them just like AWS CLI would:
> 
> ```shell
> export AWS_ACCESS_KEY_ID='' AWS_SECRET_ACCESS_KEY='' AWS_DEFAULT_REGION=us-east-1
> sops -d
> ```

That solved my problem, thank you!
