### ISSUE TITLE
Failed to get the data key required to decrypt the SOPS file.

### ISSUE THREAD

**Issue by kennyparsons** [mozilla/sops#1075]
I've seen a couple issues like this (#304 mainly) but I was not able to find a resolution. So some facts:
1. Linux Distrobution
   - debian (bullseye container)

2. GPG Version
```
gpg --version
gpg (GnuPG) 2.2.27
libgcrypt 1.8.8
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
3. SOPS Version
```
root@c33835ff9f5d:~/ssl_tls# sops --version
sops 3.7.3 (latest)
```
4. GPG Keys
```
Public:
gpg -k
/root/.gnupg/pubring.kbx
------------------------
pub   rsa4096 2022-06-17 [SC]
      E70C09A1BB13E07E06791C73617C5E776CD605CA
uid           [ultimate] redacted_name <redacted@example.com>
sub   rsa4096 2022-06-17 [E]

Private:
gpg -K
/root/.gnupg/pubring.kbx
------------------------
sec   rsa4096 2022-06-17 [SC]
      E70C09A1BB13E07E06791C73617C5E776CD605CA
uid           [ultimate] redacted_name <redacted@example.com>
ssb   rsa4096 2022-06-17 [E]
```
5. GPG TTY Set: 
```bash
env | grep GPG_TTY
GPG_TTY=/dev/pts/0
```
6. .sops.yaml:
```yaml
creation_rules:
        # The absence of a path_regex means it will match everything
        - pgp: 'E70C09A1BB13E07E06791C73617C5E776CD605CA'
```
I created the key on this container, encrypted a file, and immediately decrypted it. 
```bash
root@c33835ff9f5d:~/ssl_tls# sudo sops --encrypt --in-place test.key
[PGP]	 WARN[0000] Deprecation Warning: GPG key fetching from a keyserver within sops will be removed in a future version of sops. See https://github.com/mozilla/sops/issues/727 for more information.
root@c33835ff9f5d:~/ssl_tls# cat test.key
{
	"data": "ENC[AES256_GCM,data:dB/8C+m5Nehwbc+wQmfS9JsibA8JqG5sYx++mFbs5EpkY4NoBDbCQHWZlmeGQltdk/i1sDblpc3sMAg9kOXbHD1vYiwR1BUmNvzumNFWUVuZNdTEc2DGjTRySUIOIYH+CNppt4oWEmr1TLFgHXCPiaAc/H5Ttnq7UZQRcelaKU60ise60XEi7ea9+Pomtdj/PqcSoUAHk7rnXjNP1TFzNqtyUFTQs0Cb32tpqdNdRX4oSIDAz6H7iJw4hNe0gdHZ68c1Rbt8uSSxhGO76gyoiOrZAbW9R1E2FuiBAC3plYBFEfyi,iv:IIkV3QU8ZmbOYdhkkG8YLhnGYIqQUIh9osoUDfYpDK4=,tag:8MF1Wr7KdXoie7AOpFFNHQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2022-06-17T16:04:08Z",
		"mac": "ENC[AES256_GCM,data:lIwXd4+bbuijSLrGUdkHvaEQgtIHpKSPKziGqDfm/ZvgeeYseZ55+NUmbpF2F9E8fyZE3Ev5gZrB4DPZe54axYQEN8+oslUDCa5Wx14COnZRhWnyS/bTKlpItDbvICHE7xOkLjd5tt1dqCx38giCleMXZp2esSbywobOGYPy6DE=,iv:PNqAfzrAf31UXNUYBHI0CaMUV5VujHlLKUdjeouvKIU=,tag:/EeZepPnpYCDzPh6l5ADOw==,type:str]",
		"pgp": [
			{
				"created_at": "2022-06-17T16:04:06Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA+oXWI47kPvkAQ//ehyZiVrGdTV3SkcsAP0DgHfZgSBxH78zVmSmpVf3izaF\nZE201SPxpQgEu9G+Bwu4SOMzAOpaGoaVZySCcQPNGBOLCUcJsKchvN5BmUE07lTO\nKaE9tgvcpeihPRNOm+6roGT/uJ33j6/Es18B/prJh2PhcM0OWxOZx6Zc7Xgzi+LR\njbo2v8IVuVO6sluNDsEJmJQK2OmaUKd+l+NpnO1lMYubmHWDe3P1ULPkGeUsgJk2\nS1Ssn9oO2eJh7m8wqywK3LJzAQEngCaJghNDCz63XAK/cA/FEHmbZ35DncLuqx1J\n+GWN3S3dDrig6/WgF2JdSEzFndf6afOh5d0waeuatS3bQ097YHfbooy5sLbfZVGm\n/sSWEMF+LWOcD2+iyszhD3MxbAg9lUR/EfUrn4z7agl6pPXLmYExxcVtmcvijZDY\nYJxtfyjtcT6qi0/vQB0v9wA1DeCoFT2EsCK2TNXGDZ2vTa4YTvpm3/TXic7K9aHM\nN6r4VcQrIa6PyyGCFCgBhLAE3adBt9p5nNZrRSagenOgSH+9Wv6/DCpVkWKCzV4W\nifIcJ9KKaqpcsDv6OKSqsSZ2dE4BQlbMvdgjL28FL4sprFPjtiK+cVNJidlKa3qr\naa1RgMkh9RJeJj4o2r7qq5wX7pk18Hyu3nt3PEryWEPScxBg6RnddvZUWZ2ZUOLS\nXgGOnv5rVFFV4zwU6gxlDcsUjcjLQvTaZElAWDgGRrEdzcp9olVAhWkCwtliGgoi\nmdfiwExlTU8UJPxlicqRN0M2ahGkZTw1qNTm+MpRgB7oHU7j/Co/byWmTEqUOQI=\n=+8Y7\n-----END PGP MESSAGE-----\n",
				"fp": "E70C09A1BB13E07E06791C73617C5E776CD605CA"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}
root@c33835ff9f5d:~/ssl_tls# sudo sops --decrypt --in-place test.key
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  E70C09A1BB13E07E06791C73617C5E776CD605CA: FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: Could not
      | load secring: open /root/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

`/root/.gnupg/secring.gpg` indeed does not exist, but I don't know how to proceed. Any ideas on what to do?

**Comment by whalehub** [comment]
Just in case anyone else encounters this issue,: The GPG key has to be unlocked before it can be used to decrypt a file with SOPS.

**Comment by kennyparsons** [comment]
Yep, @whalehub and I figured out that non-interactive sops operations using gpg with passphrases is very very difficult. This is why sops recommends age.

**Comment by nelsonwellsredis** [comment]
@whalehub can you explain what you mean by "the GPG key has to be unlocked"? I'm Googled unlocking a GPG key and it hasn't lead me anywhere.

**Comment by AllenFang** [comment]
@nelsonwellsredis you need to decrypt a file by your gpg passphrase one time: that's what i did for example:

- I encrypt a file and recipient is myself
- then I decrypt this gpg file -> this step will ask you to input gpg passphrase
- after you decrypt gog file successfully, you can run the sops commend again, it will work

**Comment by drogus** [comment]
I also get this error, even with a key without password. What I fail to understand is why is SOPS looking for `secring.gpg` at all? For gpg >= 2.1 pubring.kbx is used and when I import keys gpg puts them there. What's more, locally I don't have `secring.gpg` either, but `--decrypt` works without any issues. I've also try to unlock the key earlier by doing some dummy encrypt and it doesn't change anything. The main difference between the two envs is that locally I use ubuntu and I try to decrypt on atlantis alpine image

**Comment by ophilon** [comment]
one more place to check  - got exact the same error as initial author @kennyparsons - sops works locally with pair of of users keys, but failed on remote VM.
The error seems in the terminal emulation, the tmux terminal fails:

**Comment by valkyr13** [comment]
@ophilon
It could be two of the following reasons:
 
1. You need re-generate the GPG Keys and set your passphrase to empty.
2. Or maybe you have not exported the private key using the key-id (i.e: E70C09A1BB13E07E06791C73617C5E776CD605CA) -> https://linuxhint.com/export-import-keys-with-gpg/
(silly mistake but i did make it)

good luck!

**Comment by ophilon** [comment]
Thanks for the tip @valkyr13 , my issue already closed, see #1223
An error occur in gpg due to incorrect tty.

**Comment by thegamerx1** [comment]
I ran into the same issue and making the terminal bigger, so it can ask for the password fixed it

**Comment by zzantares** [comment]
Just ran into this, my issue was that I was trying to recover from a missconfigured X session from another TTY, I did `who -u` and killed all sessions marked with `:1`, correctly set the TTY `export GPG_TTY=$(tty)` so that it used my current one, killed tmux, decrypt a file to unlock the key (`gpg --decrypt /path/to/file.gpg`) and then running `sops` worked!

**Comment by omerfsen** [comment]
Instead of giving small part of the code here is the full code snippet you can use, the GPG key is base64 encoded and put it on pipeline as secret, hence base64 decoded them, This uses gnupgv2

```bash
              export GPG_TTY=$(tty)
              export GPG_EXECUTABLE=gpg
              export SOPS_GPG_EXEC=gpg
              export GPG_AGENT_INFO=
              export GPG_OPTS="--pinentry-mode loopback"
              export SOPS_DEBUG=true
              export TERM=xterm-256color
              mkdir -p ~/.gnupg
              chmod 700 ~/.gnupg
              echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
              echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
              echo "$GPG_PRIVATE_KEY_QA" | base64 -d > private-key.asc
              echo "$GPG_PASSPHRASE_QA" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --import private-key.asc
              gpg --with-colons --fingerprint | awk -F: '/^fpr:/ {print $10 ":6:"}' | gpg --import-ownertrust
              # gpg --list-keys --keyid-format LONG
              # gpg --list-secret-keys --keyid-format LONG
              rm -f private-key.asc
              # We need to unlock gpg key before using on sops https://github.com/getsops/sops/issues/1075#issuecomment-1418239176
              secret="secret-$(openssl rand -hex 8)"
              echo "Original: $secret"
              decrypted=$(echo "$secret" | \
                          gpg -e -r "qa@email.com" | \
                          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE_QA" -d)
              echo "Decrypted: $decrypted"

```

after that you can use sops..

**Comment by ser-2007** [comment]
Thanks It works well.

**Comment by fredleger** [comment]
in case someone has the same issue as me: i ended up there after encrypting a file and a pre-commit hook reformating the sops encrypted yaml file (using yamlfix)
reverting the changes made by yamlfix fixed the issue which at first seems unrelated

**Comment by felixfontein** [comment]
@fredleger out of curiosity, what kind of changes did yamlfix do that resulted in this?

**Comment by fredleger** [comment]
@felixfontein as far as i remenber this was indent and quoting (like replace double quotes by simple ones)

**Comment by Prateek-Wayne** [comment]
> Just in case anyone else encounters this issue: The GPG key has to be unlocked before it can be used to decrypt a file with SOPS.

worked for me 💯
