### ISSUE TITLE
add --set flag to go implementation

### ISSUE THREAD

**Issue by relud** [mozilla/sops#108]

**Comment by autrilla** [comment]
Currently we use urfave/cli on the Go version, which unfortunately does not support multiple arguments for a single flag like the Python version does. So instead of:

`--set '["somekey"][0]' '{"somevalue":true}'`

We would need:

`--set '["somekey"][0] {"somevalue":true}'`

**Comment by jvehent** [comment]
That's a regression I'm not fan of introducing. Is there any way urfave/cli could support the original format?

**Comment by jvehent** [comment]
This is the last missing feature. Once implemented, we can remove the `beta` flag from go-sops 2.0.

**Comment by jvehent** [comment]
done in #160
