### ISSUE TITLE
--aws-profile option does not have the same effect as AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by L7R7** [mozilla/sops#1160]
I'm using version 3.7.3 to encrypt files using an AWS KMS key. However, it doesn't work when I set the AWS profile with the `--aws-profile` option. It works properly when I set the `AWS_PROFILE` to the correct value. If I understand the docs correctly, these two options should have the same effect. If so, this would be a bug. Am I missing something?

**Comment by kyusu** [comment]
Duplicate of https://github.com/mozilla/sops/issues/439?

**Comment by L7R7** [comment]
@kyusu you're right! closing this
