### ISSUE TITLE
sops installation is getting failed inside dockerfile

### ISSUE THREAD

**Issue by kavita1205** [mozilla/sops#1164]
Hi Team,

I am using Docker file, code is mentioned below but when I am running my jenkins CI job then its is faileing with below error
Can someone please help me why it is being failed.

Dockerfile:
'''
FROM quay.io/helmpack/chart-testing:v3.5.0
LABEL Name=ML42helmcharts Version=0.0.1

# Used to se the HELM working directory
ENV HOME=/tmp

# Install the necessary tools
RUN apk add go \ 
&& go install filippo.io/age/cmd/...@latest \
&& wget  -O /usr/local/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux \
&& chmod 700 /usr/local/bin/sops \ 
&& mkdir -p /tmp/.config/sops/age 

'''

Error
'''
The command '/bin/sh -c apk add go && go install filippo.io/age/cmd/...@latest && wget  -O /usr/local/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux&& chmod 700 /usr/local/bin/sops && mkdir -p /tmp/.config/sops/age' returned a non-zero code: 1
'''

**Comment by kavita1205** [comment]
@FnTm and @ajvb can you guys please help me here.

**Comment by michaelsatish** [comment]
Here is my working code if it helps.

```sh
ARG SOPS_VERSION=3.7.3
RUN set -ex \
    && wget --progress=dot:giga -O /usr/local/bin/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64 \
    && chmod +x /usr/local/bin/sops \
    && sops --version
```

```sh
[vscode@5880cb323b20 ~]$ sops --version
sops 3.7.3 (latest)
```

**Comment by kavita1205** [comment]
@michaelsatish Thankyou for your response but it worked when I have used latest version of chart-testing.
