### ISSUE TITLE
Deprecated project?

### ISSUE THREAD

**Issue by ChrisJBurns** [mozilla/sops#1165]
I've noticed that the `master` branch hasn't had any code merged into it since May 2022 and the `develop` branch hasn't had any changes merged to it since September 2022. Does this signal that it isn't an actively maintained project anymore? From a security perspective regular patches/fixes are imperative and since this is a security related tool, it is even more vital.

**Comment by felixfontein** [comment]
Check out #927, in particular the parts at the bottom.

**Comment by ChrisJBurns** [comment]
@felixfontein  Perfect, thank you! I still haven't embedded the habit of checking the Discussions tab yet 😄  Closing!
