### ISSUE TITLE
sops --decrypt adds trailing newline to decrypted value 

### ISSUE THREAD

**Issue by adrian-gierakowski** [mozilla/sops#1166]
and hence the following:

```sh
sops -d /path/to/encryped/secret > /path/to/decrypted/secret
```

produces a decrypted file which content is different than the original

**Comment by felixfontein** [comment]
I cannot reproduce this with sops 3.7.3. I tried encrypting both files with a trailing newline and files without one; there was no bitwise difference between original and decrypted file.

(This assumes you encrypt/decrypt files as binary data, and not as structured files like YAML or JSON files. These are decoded and re-encoded and will be semantically equivalent, but not bitwise equivalent.)

**Comment by adrian-gierakowski** [comment]
Looks like it was my editor (`nvim`) adding new line on save and I haven't realised since there is absolutely no difference in how `nvim` displays a file with or without newline at the end. Using another editor revealed that there was a newline in the file in the first place.
