### ISSUE TITLE
Community Mantainers?

### ISSUE THREAD

**Issue by enchorb** [mozilla/sops#1171]
@ajvb There are tons of open pull requests with useful new features, missing features (https://github.com/mozilla/sops/pull/1049) and bug fixes (https://github.com/mozilla/sops/pull/1155) that are not getting in.

**Comment by felixfontein** [comment]
Please see #927, especially at the bottom.

**Comment by enchorb** [comment]
@felixfontein Thanks didn't see that post, closing this
