### ISSUE TITLE
"Could not get master key" during rotation results in deleting the file

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#146]
When running `sops -r -i <file>` without having the necessary AWS permissions, sops errors with `Could not get master key` and write an empty file to disk, effectively destroying data. sops should exit and leave the file untouched.

**Comment by autrilla** [comment]
What should we do if only one of several keys fails to be updated?

**Comment by jvehent** [comment]
I think we should fail the rotation, output an error to the user and
restore the file to its original state.

**Comment by jvehent** [comment]
I'm still seeing this, so the latest patch didn't fix it.

**Comment by jvehent** [comment]
https://github.com/mozilla/sops/pull/154/commits/eafa62e1d037e242767b3d5a5e8d068ccbc0c09e fixes it!
