### ISSUE TITLE
--rm-* results in corrupted file

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#155]
When removing a KMS or PGP master key from a file, the resulting file has an invalid structure and can no longer be read.

```
$ sops --rm-kms arn:aws:kms:eu-central-1:**********:key/cb1fab90-8d17-42a1-a9d8-334968904f94 -r -i allizom.org-20161031.key

$ sops -d allizom.org-20161031.key
Error loading file: Error unmarshalling input json: invalid character 'r' after top-level value
```

Looking through the file, it looks as if the buffer used to write the file back to disk was being reused without being emptied, and string that didn't belong end up breaking the sops metadata.

```yaml
    pgp: []
    unencrypted_suffix: _unencrypted
    version: "1.14"
89e-b86c-57201e06f31e                         <--- this doesn't belong here
    pgp:
    -   fp: 6F73539153B31C193A2154EAF7A9B793541A953D
        created_at: '2016-03-17T00:11:03Z'
```

The same problem could be reproduced with KMS and PGP, and JSON and YAML files.

**Comment by autrilla** [comment]
It looks like d92680692bc20c62955ab90a38dcb76c6bac15c9 fixed this, at least on my end. Can you confirm?

**Comment by jvehent** [comment]
Yep, looks fixed from my end. 👍
