### ISSUE TITLE
Documentation to describe how to use this code directly in other Go packages

### ISSUE THREAD

**Issue by hartfordfive** [mozilla/sops#178]
Would it be possible to create some documentation that describes (with examples) how to integrate this library, without using the CLI tool, into another Go package?

**Comment by autrilla** [comment]
What exactly are you trying to do? If you want to decrypt sops-encrypted files from another Go package, https://github.com/mozilla-services/userplex/blob/master/config.go#L72-L101 is an example of doing so.

**Comment by jvehent** [comment]
We talked about providing a helper in the `sops` package that would handle decryption. Something along the line of `func DecryptData(encrypted []byte) (decrypted []byte, err error)`.

**Comment by jvehent** [comment]
This is now implemented. You can check out the doc at https://godoc.org/go.mozilla.org/sops/decrypt.
