### ISSUE TITLE
value of $EDITOR can cause sops to panic

### ISSUE THREAD

**Issue by milescrabill** [mozilla/sops#182]
to reproduce: `EDITOR=() sops` something
Obviously not the intended use of an env variable, but shouldn't panic.

**Comment by autrilla** [comment]
This doesn't panic for me, it exits with:

```
bash-4.4$ EDITOR=() sops foo
Could not run editor: exec: "()": executable file not found in $PATH
```

**Comment by milescrabill** [comment]
Interesting. I'm using zsh, and () is different than in bash.
To reproduce in bash: `EDITOR= sops foo`
