### ISSUE TITLE
Editor arguments are not supported properly

### ISSUE THREAD

**Issue by abedra** [mozilla/sops#210]
When you pass arguments to your editor sops doesn't understand them. For example:

```
export EDITOR="/usr/local/bin/emacs -nw"
```

results in the following:

```
sops file
Could not run editor: fork/exec /usr/local/bin/emacs -nw: no such file or directory
```

Removing the `-nw` makes this problem go away.

**Comment by autrilla** [comment]
This is expected because whatever is in `$EDITOR` is passed as the first argument to `exec`.

Currently we recommend creating another executable that executes your editor with whichever arguments you desire, such as:

```
#!/usr/bin/env bash
/usr/local/bin/emacs -nw
```

**Comment by autrilla** [comment]
Looking a bit more into this (thanks @ssbr) we could use https://github.com/google/shlex to split `$EDITOR` into arguments for `exec`

**Comment by abedra** [comment]
@autrilla thanks for the recommendation for the workaround. I do think it would be nice to support this in the future.
