### ISSUE TITLE
Could not load secring

### ISSUE THREAD

**Issue by exarkun** [mozilla/sops#212]
```
$ EDITOR=vi sops enc-website-secrets.yaml
Could not decrypt the data key with any of the master keys:
        [GPG]: 96B9C5DAB2EA9EB679419DB7E27B085EDEAA4B1B:        Could not load secring: openpgp: invalid data: user ID self-signature invalid: openpgp: invalid signature: hash tag doesn't match
```

Perhaps related to [this x/crypto/openpgp bug](https://github.com/golang/go/issues/11809)

**Comment by exarkun** [comment]
Or, I don't know, maybe not.  It fails exactly the same way with a brand new key, too.

**Comment by jvehent** [comment]
Do you use gpg2? If so, maybe you're problem is similar to #189.

**Comment by exarkun** [comment]
Yes:

```
$ gpg --version
gpg (GnuPG) 2.1.15
```

**Comment by exarkun** [comment]
I upgraded to the Python version, problem is resolved.  Thanks.

**Comment by jvehent** [comment]
Sops 2 won't work then. Try using the legacy Sops 1, which was written in Python and shells out to the gpg executable. `pip install sops`.

Closing this issue as supporting gpg2 in Sops 2 is being discussed in #189.
