### ISSUE TITLE
Add a means to report security issues

### ISSUE THREAD

**Issue by NeilMadden** [mozilla/sops#219]
I currently cannot see any way to report security issues for this project. If you do not want these to be raised as normal issues (i.e., immediate public disclosure) then it would be a good idea to add an email address + PGP key or similar that can be used to report security issues.

(I have issues to report, so this is quite pressing).

**Comment by jvehent** [comment]
You can contact me privately using jvehent@mozilla.com. My PGP key is available at https://keybase.io/jvehent

**Comment by NeilMadden** [comment]
Message sent. I am https://keybase.io/neilmadden

**Comment by NeilMadden** [comment]
This appears to be resolved now with a section on reporting security issues in the README. Thanks.
