### ISSUE TITLE
Use a 96-bit nonce for the IV

### ISSUE THREAD

**Issue by NeilMadden** [mozilla/sops#220]
Currently your code uses a 256-bit random IV (nonce) for AES-GCM. GCM is designed to use a 96-bit nonce and if you give it a longer (or shorter) value it hashes it to obtain a value of the correct length (see Algorithm 4 of [NIST SP.800-38D](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf). As you are using random IVs anyway, this doesn't change much from a security perspective, but it is inefficient to use a 256-bit value here when 96-bits is all that is required (after base64-encoding you are adding about an extra 27 bytes to each encrypted value).

Note that the IV for GCM does not need to be random, it just needs to never repeat for the same key (a nonce: see the Deterministic IV Construction in Section 8.2.1 of the linked specification). As you are generating fresh random 256-bit AES keys for each file and processing the whole file at once, I would suggest just keeping a simple counter that you increment for each value that you encrypt in the file: 0 for the first, 1 for the second etc. Encode this as a 96-bit value (e.g. big-endian) and use that as the nonce. That way you do not need to explicitly record the IV at all.

**Comment by autrilla** [comment]
But if we did what you suggest, when editing a file, we'd end up reusing IVs. Alternatively we could record the biggest IV we saw on the file when decrypting it, and start from that when reencrypting.

I don't know if there's any big advantage in doing this compared to just generating a random number, though.

**Comment by NeilMadden** [comment]
If you reuse the same key when editing then yes, it is safer to generate random IVs. Just make sure never to generate more than 2^32 random IVs for the same key ever as with 96-bit IVs the likelihood of a collision becomes a bit high after that.
