### ISSUE TITLE
Encrypting textfile with only numeric values as content can not be decrypted again

### ISSUE THREAD

**Issue by aberresch** [mozilla/sops#235]
Problem:

I have stored a textfile with content "20170824" and encrypt it with sops. If I try to
decrypt the textfile I got the following message:

**Error dumping file: No binary data found in tree**

Here are the steps to reproduce this issue:

1.) echo "20170824" > test.txt
2.) AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=${AWS_PROFILE} SOPS_KMS_ARN=${SOPS_KMS_ARN} sops -e test.txt > test.txt.enc
3.) AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=${AWS_PROFILE} sops -d test.txt.enc

REMARK: If I add a non-numeric value to the existing content it works!

**Comment by autrilla** [comment]
This seems to work with the Python version, it's a bug in the Go version.
