### ISSUE TITLE
Release 2.0.10 still reports 'sops 2.0.9 (latest)'

### ISSUE THREAD

**Issue by JCount** [mozilla/sops#237]
In the latest release, it appears that [sops/blob/2.0.10/cmd/sops/version.go#L13](https://github.com/mozilla/sops/blob/2.0.10/cmd/sops/version.go#L13) accidentally missed getting bumped. 

This leads to compiled version `2.0.10` programs erroneously reporting `sops 2.0.9 (latest)` when `sops --version` is run.

(I apologize for the messy issue, I somehow managed to hit `CMD+ENTER` while composing the title.)

**Comment by mrgleeco** [comment]
Looks like a bunch of great things added in the interim (GCE!).  Any idea on next release date?

**Comment by autrilla** [comment]
I want to merge #255 and #256 before 3.0, so however long it takes to review. Those should be reviewed within the next two weeks.

**Comment by jvehent** [comment]
sops 3.0.0 is reviewed
