### ISSUE TITLE
Reconfigure the keys in a directory using the content of .sops.yaml

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#243]
`.sops.yaml` may contain keys that are added and removed over time. We currently don't have an easy way to propagate changes to `.sops.yaml` to files in a repository. It would be nice to have a `key-sync` command that processes every file and adds or remove keys according to the config.

Ideally, this is interactive and for each file shows which keys are being added/removed.

**Comment by autrilla** [comment]
Implemented in #255
