### ISSUE TITLE
Consistent url to the latest release.

### ISSUE THREAD

**Issue by maximrybalov** [mozilla/sops#254]
It would be helpful if you offered a consistent url to latest compatible packages release.
Something along the lines of https://github.com/mozilla/sops/releases/download/2/sops_2_latest_amd64.deb would always point to the latest release of sops2.
This way automated build system will always include the latest version without having to manually bump up the version every time there's a release.

**Comment by jvehent** [comment]
You can do this by querying the github api:
```bash
$ curl https://api.github.com/repos/mozilla/sops/releases/latest | jq '.assets[] | select(.name | contains("rpm")) | .browser_download_url'
"https://github.com/mozilla/sops/releases/download/3.0.0/sops-3.0.0-1.x86_64.rpm"
```
