### ISSUE TITLE
sops with ssh

### ISSUE THREAD

**Issue by mrgleeco** [mozilla/sops#280]
wondering if possible to use sops to decrypt an ssh key.  This is obvious example but doesn't work:

```
ssh -i <(sops -d foo.key) foo@bar
```

if it is possible, consider adding info to docs as a helpful guide for users

**Comment by autrilla** [comment]
I'm not sure how this is SOPS's fault. `ssh -i <(cat foo.key) foo@bar` won't work either.

**Comment by mrgleeco** [comment]
not a bug! - nor issue per se; rather just a helpful guide / example if it *can* be done

**Comment by conorsch** [comment]
@mrgleeco You may find direct use of GPG for file encryption to be more convenient for your use case. That said, try this:

1. Run `sops sshkey.yml` to create a new SOPS-encrypted file.
2. Add a top-level key called `ssh_key1` (the name can be anything, but you'll need it later).
3. Paste in the SSH private key. Make sure to use the `ssh_key1: |` syntax for a multiline YAML value.
4. Save and exit.

Then you can call sops with the `--extract` option to retrieve just the value:

```
ssh -i <(sops -d --extract '["ssh_key1"]' sshkey.yml | tail +2)
```

The `--extract` option lets you select a single var. The `| tail +2` omits the first line of output, which is `|`, given the multiline YAML syntax mentioned above.

Hope that helps!

**Comment by autrilla** [comment]
Closing in favor of #337

**Comment by anibal-aguila** [comment]
Hi @conorsch, how I can do this whit ~/.ssh/config file?

```
Host eu-east-server
    HostName 188.108.87.83
    PreferredAuthentications publickey
    IdentityFile <(sops -d --extract '["ssh_key1"]' /home/aa/00/ate/src/00-demoSecret/ops/sshkey.yml)
    IdentitiesOnly yes
    Port 28970

```
