### ISSUE TITLE
Examples for --set and --extract do not work as described

### ISSUE THREAD

**Issue by dsclementsen** [mozilla/sops#285]
After having set up sops and gpg to have a play with sops, I find that the examples for the --set and --extract flags do not work as they stand.

**For `--extract`, the examples in README.rst are:**

`sops -d ~/git/svc/sops/example.yaml --extract '["app2"]["key"]'`
and
`sops -d ~/git/svc/sops/example.yaml --extract '["an_array"][1]'`

For me, neither of these will print only the desired key, but rather the whole file is decrypted and printed to stdout.  I did get it to work in a different parameter order though, like so the single key value is output.

`sops -d --extract '["app2"]["key"]' ~/git/svc/sops/example.yaml`
and
`sops -d --extract '["an_array"][1]' ~/git/svc/sops/example.yaml`

Not sure if this is a simple documentation issue, or not "working as desired".

**For `--set`, the examples in README.rst are:**

`sops ~/git/svc/sops/example.yaml --set '["app2"]["key"]' '"app2keystringvalue"'`
`sops ~/git/svc/sops/example.yaml --set '["an_array"][1]' '"secretuser2"'`
and
`sops ~/git/svc/sops/example.yaml --set '["an_array"][1]' '{"uid1":null,"uid2":1000,"uid3":["bob"]}'`

For me, none of these work as described. Instead, the entire file is decrypted and opened in `vim` (my configured `$EDITOR`).  Here, unlike for `--extract`, I did not find any alternative order of params that works.

(If it helps, I'm on MacOS High Sierra, `gpg --version` "gpg (GnuPG) 2.2.4 libgcrypt 1.8.2", `sops -v` "sops 3.0.0")

**Comment by autrilla** [comment]
I believe this is a documentation issue. With the command line parser we use in Go, there can't be any flags after the file name. Also, flags must be a single string, so for `--set`, `'["an_array"][1]' '"secretuser2"'` won't work as those are two strings. `--set '["an_array"][1] "secretuser2"'` should work, though.
