### ISSUE TITLE
[bug] reported issue with python 3.5

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#29]
no details yet, needs investigation
should add testing in travis

**Comment by jvehent** [comment]
@ckolos : got any details on the failure you're encountering?

**Comment by ckolos** [comment]
1) Check out repo to ./sops
2) run ```virtualenv --no-site-packages sops```
3)  ```cd sops && bin/activate```
4) ```pip install -U sops```
5) Wall of text: https://gist.github.com/ckolos/b0f75977979355402a90

I suspect this is a case of the upstream packages being borked in some way or maybe my machine/build-env

**Comment by jvehent** [comment]
Could you insert some package install as step 0?
`sudo yum install libyaml-devel python-devel libffi-devel pip`
`sudo apt-get install libyaml-dev python-dev libffi-dev python-pip`
or whatever archlinux uses...
