### ISSUE TITLE
Make integrity check optional

### ISSUE THREAD

**Issue by yagnik** [mozilla/sops#294]
We have a use case wherein we want all the developers to update the json file but still have the ability to decrypt. Currently the integrity check causes the decryption to fail if the files are edited outside sops. The other option is to force all our devs to use sops to edit.
Do you think it's a good idea to make the check optional ?

**Comment by autrilla** [comment]
Is `--ignore-mac` not what you're looking for?

**Comment by yagnik** [comment]
Totally is, my mistake, I should have looked through properly. Thank you!
