### ISSUE TITLE
GCP KMS not decrypting error

### ISSUE THREAD

**Issue by roger-rainey** [mozilla/sops#299]
if I have a simple test.yaml file:
test: 'test value'

and run:
sops --encrypt --gcp-kms path_to_key test.yaml > test.yaml.enc 
This produces an encrypted key, but when I run:
sops --decrypt test.yaml.enc
I get the following output:
Error loading file metadata: Error unmarshalling input json: invalid character 'e' in literal true (expecting 'r')

Any clues would be helpful

**Comment by autrilla** [comment]
SOPS auto-detects file type based on its extension and defaults to "binary"
(which is secretly JSON) if it's an unknown extension. ".enc" is one such
extension. Change the file name from test.yaml.enc to test.enc.yaml and it
should work.
