### ISSUE TITLE
Azure KeyVault support

### ISSUE THREAD

**Issue by omerlh** [mozilla/sops#310]
Azure KeyVault is pretty similar to KMS and can be used to wrap/unwrap keys. Are than plans to support it? I might have time to contribute the code, but I wanted to ask before starting to work on it.

**Comment by autrilla** [comment]
We don't have any plans to support it (that I know of), but a PR would certainly be welcome!

**Comment by omerlh** [comment]
Cool, I hope to actually do it :)
