### ISSUE TITLE
multi-line value extracts incorrectly

### ISSUE THREAD

**Issue by hobti01** [mozilla/sops#321]
Have I overlooked something with `--extract`?
```
$ sops -d /tmp/test.yaml
street: |
    123 Ave
    Room 5
```
Unexpected pipe and indentation when using `--extract`:
```
$ sops -d --extract '["street"]' /tmp/test.yaml
|
    123 Ave
    Room 5
```

Expected to [match the documentation](https://github.com/mozilla/sops#45extract-a-sub-part-of-a-document-tree):
```
$ sops -d --extract '["street"]' /tmp/test.yaml
123 Ave
Room 5
```
```
$ sops --version
sops 3.0.2 (latest)
```

**Comment by autrilla** [comment]
This was fixed by #317 and will be available in the next release
