### ISSUE TITLE
Add the ability to specify  --unencrypted-suffix in the .sops.yaml file

### ISSUE THREAD

**Issue by dovreshef** [mozilla/sops#324]
Hi

It would help my use cases to specify the  --unencrypted-suffix in the creation_rules section in the .sops.yaml.

Is that something that you'd consider? I'm willing to implement it.

**Comment by autrilla** [comment]
Yes, this is a feature we would merge. I assume you'd also want support for --encrypted-suffix too?

**Comment by dovreshef** [comment]
@autrilla Yes :). 
Will finish working and --encrypted-suffix and start on this.
