### ISSUE TITLE
embedded sops engine

### ISSUE THREAD

**Issue by mrgleeco** [mozilla/sops#329]
hello - general information question; i'm wondering if there is prior art or thoughts from the team here:

would be possible to embed the sops decryption engine in some other go project?
For example, a golang server that decrypts files sent to it.

...any guidance is most appreciated!

**Comment by jvehent** [comment]
Absolutely! Take a look at the loadFromFile function on autograph for an
example we use in production:
https://github.com/mozilla-services/autograph/blob/master/main.go
