### ISSUE TITLE
Remove python module

### ISSUE THREAD

**Issue by dedsm** [mozilla/sops#331]
Hello,

it seems the python module is abandoned, I've been trying to use it but it has some fixed dependencies in very old packages like cryptography==1.4 (latest cryptography version is 2.2.2).

In my opinion it should be deprecated since it doesn't seem to be supported.

**Comment by autrilla** [comment]
I'm not sure why having old dependencies means it should be removed. Can you explain why you think this should be the case? The Python version is in maintenance mode, so only bugs and known security issues are fixed. PRs to the Python version are naturally also welcome. We want people who want to keep using the Python version to be able to continue to do so. Removing the package will break existing systems, so I don't think we'll do that any time soon.

**Comment by dedsm** [comment]
well, cryptography can't be installed with latest openssl library versions, maybe removing is not correct, but at least specify it's not actively developed? you can't just install sops with pip as the documentation says.

I noticed an issue raised a while ago about precisely the cryptography module https://github.com/mozilla/sops/issues/126
