### ISSUE TITLE
Better error message for audit db connection failing

### ISSUE THREAD

**Issue by ajvb** [mozilla/sops#347]
At the moment, the error message for failing to connect to the audit db is:

```Pinging audit database failed: <error message>```

I've seen two cases where a user had a `/etc/sops/audit.yml` file and had forgotten about it and the above error is all they get.

Should include further information on where the file is, what's going on, etc.

**Comment by olevchyk** [comment]
@autrilla can we consider this as solved ?

**Comment by autrilla** [comment]
Yes! Thanks for reminding me!
