### ISSUE TITLE
sops -r w/--add-pgp flag always sends output to STDOUT, doesn't modify file

### ISSUE THREAD

**Issue by jc00ke** [mozilla/sops#349]
We're using sops to manage shared credentials for the Portland Ruby Brigade. In trying to add a key in pdxruby/creds#1 I noticed that

```
> sops -r --add-pgp 42somePGPkey twitter.yaml
```

always sent output to `STDOUT` and *would not* modify the file. I would expect that this command would add the key and rotate, not send output to `STDOUT`. I had to

```
> sops -r --add-pgp 42somePGPkey twitter.enc.yaml
> mv twitter.enc.yaml twitter.yaml
```

which seems to contradict [this section of the `sops` README](https://github.com/mozilla/sops/tree/5430b6387961681ae40379fae57979d95496a721#adding-and-removing-keys). Am I doing something silly, or missing something subtle?

This is on `sops 3.0.3` with `gpg2 2.2.6`.

Thanks!

**Comment by ajvb** [comment]
Hey @jc00ke, I can see how the documentation is a tad bit confusing. I believe you want to add the `-i` flag to your command, which will modify the file in place.
