### ISSUE TITLE
Update vendoring for Azure/go-autorest

### ISSUE THREAD

**Issue by carlpett** [mozilla/sops#360]
There was a bug in one of the Azure libraries used in #358 which manifested on some machines if the required credentials were not set at all (ie, not invalid credentials, but missing altogether). This has been fixed upstream, and the vendored Azure/go-autorest needs an update.

As a related question, it seems you do not check in the `vendor.yml` file from govend, which makes it quite hard to work with - if I try to do `govend -u github.com/Azure/go-autorest` it removes all other vendored libraries for example. Would it be possible to add? Would also make it easier to know which versions of things are in use.

**Comment by autrilla** [comment]
If we're going to start changing how we do vendoring, we should just switch to `dep` imo.  I've opened #361 with the update.

I did this by:

```bash
rm -Rf ./vendor/github.com/Azure/go-autorest
govend github.com/Azure/go-autorest
```

Not very pretty...
