### ISSUE TITLE
Discussion: Embed SOPS functionality in other process

### ISSUE THREAD

**Issue by carlpett** [mozilla/sops#363]
[Moving conversation from IRC]
I'm looking into how other programs could embed SOPS decryption/encryption, rather than exec:ing the sops binary. My use-case is creating a [Terraform](https://terraform.io) data provider which utilizes SOPS encrypted files as input. For context, Terraform manages infrastructure, and thus frequently needs access to secrets. Its configuration is also frequently stored in version control, so getting those secrets to the configuration is a problem.

Currently, we do something like this:

```hcl
variable "demo-secret-foo" {}
output "do-something" {
  value = "${data.sops_file.demo-secret.data.foo}"
}
```

And then initialize the variable by doing process redirection when invoking terraform: 
`$ terraform apply -var-file <(sops -d demo-secret.enc.json)`

What we *want* is a Terraform integrated experience, more like this:

```hcl
provider "sops" {
  keyservice = "localhost:5000" # Note: From IRC I gathered this might not actually be what I want
}

data "sops_file" "demo-secret" {
  source_file = "test.json"
}

output "do-something" {
  value = "${data.sops_file.demo-secret.data.foo}"
}
```

(For this simple case, it becomes a few more lines of code, but when there are dozens of secret files it is a lot more attractive...)

A Terraform provider is basically a small Go program, so this is a rather generic question about how it is/should be/should not be possible to having access to the encrypt/decrypt facilities in cmd/sops as an library.

The Keyservice gRPC binding was my first idea, but this may be too low level.

**Comment by jvehent** [comment]
Assuming you can write a provider in Go, you could use the `decrypt` package to load an encrypted file into terraform. Here's an example of how another Go program loads an encrypted Sops file as its configuration, then unmarshals the yaml: https://github.com/mozilla-services/autograph/blob/master/main.go#L124-L149

**Comment by carlpett** [comment]
Thanks! And after some more discussions on IRC, I think we can close this.
