### ISSUE TITLE
Re-read .sops.yaml for key rotation (-r)

### ISSUE THREAD

**Issue by hobti01** [mozilla/sops#365]
Adding or removing a key within .sops.yaml and rotating keys does not add or remove keys from the encrypted file.

Is this intentional and if so, could there be a flag to change this behaviour instead of a full decrypt/encrypt?

Example:
```
# Create configuration file with some fingerprints
vi .sops.yaml

# Confirm fingerprint in configuration file
$ grep 4BF .sops.yaml
  - pgp: '4BF...'

# Create test file
$ sops tester.yaml

# Verify fingerprint is in file
$ grep 4BF tester.yaml
        fp: 4BF...

# Remove fingerprint from configuration file
vi .sops.yaml

# Verify fingerprint is removed from configuration
$ grep 4BF .sops.yaml

# Rotate keys 
$ sops -r -i tester.yaml

# Observe that fingerprint remains in file <-- unexpected?
$ grep 4BF tester.yaml
        fp: 4BF...

# Re-encrypt and verify fingerprint is removed
$ sops -d -i tester.yaml && sops -e -i tester.yaml && grep 4BF tester.yaml

**Comment by autrilla** [comment]
That's not what the rotate mode does. Rotate rotates the *data* key (the AES key used to encrypt the document), not the master keys. I think you're looking for `sops updatekeys`.

**Comment by hobti01** [comment]
ah, yes I think I am :)  
`sops updatekeys -y tester.yaml`

Just to confirm, this also rotates the data key or I should also provide `-r`?

**Comment by autrilla** [comment]
No, this does not rotate the data key, you'll have to do that manually.

But now that I think about it, I think we should change it so that it does... in the case where you're removing a master key from the file, I think you have to rotate the data key, as you want people who previously had access to that key to stop having access to the file, so if you keep the same data key, they can still decrypt the file... thoughts @jvehent ?

**Comment by autrilla** [comment]
No, the updatekeys subcommand does not take `-r` as an option.

You should run `sops updatekeys -y tester.yaml && sops -r -i tester.yaml`

**Comment by jvehent** [comment]
I think it's best to keep the two operations (update keys and rotate data
key) separate and maybe add an entry in the readme and a warning in the
logs to be explicit.
