### ISSUE TITLE
Provide development build instructions

### ISSUE THREAD

**Issue by max-wittig** [mozilla/sops#371]
I'm not able to build the project to contribute fixes or feature.

Build instructions for development would really help here.

**Comment by autrilla** [comment]
This is a standard Go project, so depending on what you want to build just:
- `go build go.mozilla.org/sops` for the library
- `go build go.mozilla.org/sops/cmd/sops` for the CLI tool
- `go install go.mozilla.org/sops/cmd/sops` to install the CLI tool
