### ISSUE TITLE
Encryption process strips leading comments

### ISSUE THREAD

**Issue by grantbachman** [mozilla/sops#374]
I'm using Sops 3.05, and found that if a file contains a leading comment, like in the example below, it is completely absent in the encrypted version of the file. Is there a reason for this or is this just a bug?

```yaml
# Comment
key: value
# Another Comment
```

**Comment by autrilla** [comment]
This is a known bug (see https://github.com/mozilla/sops/issues/300#issuecomment-367942757). The reason for this is that it was too complicated to support this in [our YAML parser](https://github.com/mozilla-services/yaml).

**Comment by grantbachman** [comment]
Thanks for the quick reply! Completely understandable. It seems more and more tools are written in Go, which I don't yet know...
