### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by nphmuller** [mozilla/sops#375]
I'm really looking forward to trying out the Azure KeyVault integration that has recently been implemented. 
Do you have any idea when the next version might be released? Are there still some issues that block the next release?

**Comment by holmesb** [comment]
Indeed, Azure KeyVault integration seems a significant enough feature to warrant a release if there aren't any show-stoppers.

**Comment by jvehent** [comment]
we'll go through pending issues and changelog with @autrilla and cut a release next week

**Comment by autrilla** [comment]
Version 3.1.0 has been released with Azure Key Vault support

**Comment by patrickmslatteryvt** [comment]
The latest release is still tagged with the `v3.0.5` release version
See: https://github.com/mozilla/sops/compare/3.1.0?expand=1

```
docker container run -it --rm mozilla/sops:latest sops --version
sops 3.0.5 (latest)
```

**Comment by autrilla** [comment]
Looks like I messed up the release :(. I'll release 3.1.1 tomorrow with the version number added, but I thought @jvehent's CI check prevented the release from being published if the version wasn't set properly.
