### ISSUE TITLE
Use vscode as editor for sops

### ISSUE THREAD

**Issue by gheibia** [mozilla/sops#380]
I can't seem to get `sops` to work with `Visual Studio Code` as its editor in Windows. `vscode` is already in the PATH. However, `sops` prints the decrypted content on the console instead of opening the editor.

```
c:\>code .
----^ this opens the Visual Studio Code editor

c:\>echo %EDITOR%
"code"

c:\>sops-3.1.0.exe --decrypt encrypted.txt
Decrypted content
```

**Comment by autrilla** [comment]
Please see #127

**Comment by gheibia** [comment]
Thanks. In this case I should be using `code --wait`

**Comment by misak113** [comment]
I made an extension for VSCode to automatic decrypt -> edit -> encrypt sops yaml/json file in-place.
Maybe it helps someone
https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops
