### ISSUE TITLE
Sops breaks entry with spaces into multiple lines

### ISSUE THREAD

**Issue by sc250024** [mozilla/sops#388]
## Description

When encrypting SQL Server connection strings in Dotnet core, it seems Sops does not like the spaces, and breaks the connecting string into multiple lines. Even when I explicitly quote the connection string, it still does not work.

Here's what I enter into a `secrets.yaml` file using Sops:

```yaml
extraVars:
    Authentication_ConfigurationOptions__AuthorizationConnectionString: "data source=mydatabase.company.com,1433;initial catalog=somedatabase;user id=someuser;password=somepassword;MultipleActiveResultSets=True;"
```

## Expected Behavior

Running `sops -d secrets.yaml` produces the same result:

```yaml
   1 extraVars:
   2     Authentication_ConfigurationOptions__AuthorizationConnectionString: data source=mydatabase.company.com,1433;initial catalog=somedatabase;user id=someuser;password=somepassword;MultipleActiveResultSets=True;
```

## Actual Behavior

Sops line breaks on the spaces. Running `sops -d secrets.yaml` on the example above produces:

```yaml
   1 extraVars:
   2     Authentication_ConfigurationOptions__AuthorizationConnectionString: data source=mydatabase.company.com,1433;initial
   3         catalog=somedatabase;user id=someuser;password=somepassword;MultipleActiveResultSets=True;
```

## Steps to Reproduce the Problem

Follow my example above.

## Specifications

  - Version: sops 3.1.1 (latest)
  - Platform: macOS

**Comment by jvehent** [comment]
I can reproduce on Linux with both vim and nano as editor. I think it might be a quirk of the yaml library, but I don't get the issue when extracting the value with `--extract`:
```bash
$ sops -d --extract '["extraVars"]["Authentication_ConfigurationOptions__AuthorizationConnectionString"]' somefile.yaml 
data source=mydatabase.company.com,1433;initial catalog=somedatabase;user id=someuser;password=somepassword;MultipleActiveResultSets=True;
```

**Comment by sc250024** [comment]
@jvehent I see what you mean. I see also that the value is returned normally using `--extract`, however when we deploy that secret YAML file to Kubernetes, it gets broken into multiple lines, and doesn't work.

**Comment by autrilla** [comment]
It also works as expected if you output as JSON (with `--output-type json`), so this looks like an issue with our YAML library

**Comment by autrilla** [comment]
Actually, I don't think this is a bug. It's perfectly valid for the YAML library to do this, as YAML allows breaking lines like this. If you load the outputs into http://www.yamllint.com/, you can see they're equivalent.

**Comment by autrilla** [comment]
Sorry, I'm failing to understand why this is an issue. It's a stylistic detail, the data itself is not changed. You don't need to perform any checks. Your input and output YAML contains exactly the same data for all your examples.

go-yaml tries to break lines if they exceed 80 characters. Lines can only be broken at certain places, of course, which is why you see this happen with spaces.
