### ISSUE TITLE
[feature request] partially encrypt file by using multiple suffix flags

### ISSUE THREAD

**Issue by nodox** [mozilla/sops#390]
Right now you can partially encrypt a file using the `--encrypted-suffix <NAME>` option. However I would like to add multiple of these flags so that it can encrypt multiple entries based on different `key` names that I pass it. How can I partially encrypt a file in this manner or when could we expect a feature like this?

**Comment by secret104278** [comment]
My workaround is use `--encrypted-regex`

For example
```
adminPassword: some_secret
access_key: some_secret
secret_key: some_secret
```
I use `--encrypted-regex "([Pp]assword)|([Kk]ey)"` so that only key end with password or key will be encrypted.
