### ISSUE TITLE
make_download_page.sh can fail to generate output

### ISSUE THREAD

**Issue by coretemp** [mozilla/sops#394]
https://github.com/mozilla/sops/blob/master/make_download_page.sh can fail to generate output, because the `aws s3` can fail.  

I don't really see what the point of automation is, if you do it incorrectly.

**Comment by autrilla** [comment]
We welcome contributions to fix this issue, if you're smarter than us and can do it correctly 😉 .

Why are you generating this anyway?

**Comment by autrilla** [comment]
> We welcome contributions to fix this issue, if you're smarter than us and can do it correctly 😉 .

**Comment by jvehent** [comment]
I don't know if you're smarter, but you're certainly a pompous ass. We
welcome contribution from people interested in helping, not from people
looking for self agrandissement.

This shell script is such an unimportant part of the Sops project that I
propose to close this issue as wontfix.

**Comment by autrilla** [comment]
Works for me 😄
