### ISSUE TITLE
Use HOME to detect gpg home

### ISSUE THREAD

**Issue by jkroepke** [mozilla/sops#397]
In some setups sops is running as part of helm secrets inside a docker container for example inside a jenkins ci.

In this setup its possible to start the container with an user or uid which in unknown to the container (no passwd entry). But environment variables like HOME etc are defined by the CI.

Now at some point we get errors like

```
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  9470EDC9DC2739938500DD8C961D45F322EDDB7F: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open ~/.gnupg/secring.gpg: no such file or directory; GPG
      | binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

But `ls ~/.gnupg/secring.gpg` works like a charm. Also `gpg --import` and all other gpg commands are working flawlessly.

After some troubleshooting we detect if we set `GNUPGHOME=$HOME/.gnupg/` the problem is gone and sops can read successfully the secring.gpg which means that the `~` will not evaluate to the current home. It looks like sops will look for a directory named `~`.

See: 
https://github.com/mozilla/sops/blob/8c8d780abb1bbc767ee0452ff352dd2ac1148392/pgp/keysource.go#L245

https://github.com/mozilla/sops/blob/108e66f46f07a3c5dd0717d298f15558594baba6/pgp/keysource.go#L249

From my side I would change the function, for example if `user.Current()` is nil look for a `HOME` environment variable. If there is no HOME defined fail here with an message like can not find pgp home.

If you really want to auto detection of the home directory of gpg, try something like:

```
# gpg --version | grep Home
Home: /Users/jan/.gnup
```

**Comment by autrilla** [comment]
Yeah, I think you're right. I'm pretty sure `"~/.gnupg"` has never worked. Thanks for submitting the issue. I don't really have the time to implement this right now, but I'd be willing to review a patch that uses `HOME`, or also calls the `gpg` binary to find the correct location.

**Comment by jkroepke** [comment]
> but I'd be willing to review a patch that uses `HOME`

https://github.com/mozilla/sops/pull/398 I'm to a go export but it looks good enough.

> or also calls the gpg binary to find the correct location.

On my tests I see that if passwd and HOME isn't defined for the current usue gpg will return just `~` which is not helpful in this situation.

```
gpg --version | grep Home
Home: ~/.gnupg
```

**Comment by jkroepke** [comment]
Thanks for the quick investigation.
