### ISSUE TITLE
Provide examples of SOPS setups

### ISSUE THREAD

**Issue by twolfson** [mozilla/sops#40]
As a newcomer to secret management (used to either an ignored file or committing into memory but in a private repo), I had trouble figuring out how to apply SOPS to my current setup (e.g.would I load into memory at boot? do I store in plaintext on disk?). After enough reasoning, I resolved that:

- Loading into memory at boot isn't great for cross-language
    - Requires per-language implementation which is bad for security since higher chance of human error
    - If someone uses an autoloader like `nodemon` which restarts server upon changes during development, then that can get costly with AWS (could use caching but then we are storing in disk)
- Plaintext on disk is fine because if attacker gains server access then they can run `sops --decrypt` and look at secrets

However, to prevent all future newcomers from running into the same hurdles, I suggest we add an examples section.

I have thought of 2 configurations that might be nice to showcase:

**Catch-all secrets file:**

- File inside of configuration folder (e.g. `config/secret.enc.yml`) which contains all secrets
- Upon plaintext decryption, store without `.enc` suffix (e.g. `config/secret.yml`)
- Ignore `config/secret.yml` via `.gitignore` or similar
- In other configuration files, load in `config/secret.yml` and use in respective configurations

Here's an example setup:

https://github.com/twolfson/twolfson.com/blob/3.79.0/config/secret.enc.json

https://github.com/twolfson/twolfson.com/blob/3.79.0/config/static.js#L14

https://github.com/twolfson/twolfson.com/blob/3.79.0/bin/decrypt-config.sh

**Secrets in each file:**

This setup will likely be more sane once #24 is resolved but each secret would be managed inline in each file. This would be practical if developers want to visually cross-check test vs production values easily.

- Store all secrets inlined in encrypted configuration files (e.g. inside `config.enc`)
- Decode all files from `config.enc` to `config`
    - Bonus points for scripting editing + syncing automatically
    - https://github.com/twolfson/twolfson.com/blob/12a84f0c66bf10f80ae18e26c8d306779ce88b47/bin/edit-config-file.sh
- Ignore decrypted files via `.gitignore` for `config`

**Comment by jvehent** [comment]
I agree that adding a few use cases to the doc would be valuable. Do you think you could attempt to phrase something together and send a PR on the readme?

**Comment by twolfson** [comment]
Cool, what are your thoughts on an `examples` or `docs` directory with a link from the README? It might prove to be more approachable since people can interact with it.

**Comment by jvehent** [comment]
A `docs` directory with various `user stories` seems like a reasonable approach. I would give us room to introduce the context of each use case without bloating the readme.

**Comment by twolfson** [comment]
Cool, I will take a look at this by the end of the weekend :+1:

**Comment by twolfson** [comment]
I am going to hold off on taking care of this issue until #24 is resolved as it will make the examples for "Secrets in each file" more approachable

**Comment by twolfson** [comment]
Now that #24 is resolved, I'm going to take a look at working on this.

**Comment by twolfson** [comment]
Alright, PRs #50 and #51 are up :tada:

**Comment by jvehent** [comment]
And the readme is updated. We're good to close this, thank you @twolfson !

**Comment by twolfson** [comment]
:+1: :tada:
