### ISSUE TITLE
No auditing when started as keyservice

### ISSUE THREAD

**Issue by paulyeti** [mozilla/sops#405]
When sops is used without `--keyservice`, auditing to postgresql db works.
However, when sops is started as follows:
`$ /usr/local/bin/sops keyservice --net tcp --addr 127.0.0.1:5100 --verbose`
and the keyservice is used remotely via ssh port forwarding, then no events are added to the db table, even though the above command outputs 1line for each remote encryption/decryption to the terminal.

Is this a bug or just not implemented ?

BTW: Only successful encrypt/decrypt actions are logged. Can encryption/decryption failures not be logged ?

Thanks and best regards

**Comment by ajvb** [comment]
>Is this a bug or just not implemented ?

Purposefully not implemented. The Keyservice is meant as a mechanism for remotely accessing keys on your machine, where you are running `sops` somewhere else. This "somewhere else" is where the audit events will be stored.

>BTW: Only successful encrypt/decrypt actions are logged. Can encryption/decryption failures not be logged ?

That is a good point, will create an issue for that.

**Comment by paulyeti** [comment]
OK, thanks. I assumed it would be logged on the keyservice side. But in that case that might be even better, since then the name of the user consuming the sops secrets would be logged to the db and not the name of the user running the sops keyservice, correct ?
You can close this issue.
Have a nice day.

**Comment by autrilla** [comment]
> But in that case that might be even better, since then the name of the user consuming the sops secrets would be logged to the db and not the name of the user running the sops keyservice, correct ?

Yup, that's right
