### ISSUE TITLE
Creating a new dotenv file with sops fails

### ISSUE THREAD

**Issue by chrisrink10** [mozilla/sops#419]
If I attempt to create a secret `.env` file using `sops`, I get an error and cannot proceed:

```
$ sops -v
sops 3.2.0 (latest)
$ sops etc/secret.env
cannot use complex value in dotenv file: [example_value1 example_value2]
```

However, I don't get the same error trying to do the same workflow with a `.yaml` file:

```
$ sops etc/secret.yaml
# Takes me to vim to edit etc/secret.yaml ...
File has not changed, exiting.
```

I don't experience this error if I'm opening an existing file. 

I was able to workaround this issue doing this:

```bash
touch nonsecret.env \
  && sops -e nonsecret.env > secret.env \
  && rm nonsecret.env
```

**Comment by matejaputic** [comment]
This solution worked for me, thank you @chrisrink10 .

It seems that you can't just set up a creation rule like this:
```
creation_rules:
  - path_regex: \.env$
    input_type: dotenv
    age: <agekey>
```
You have to use the above method to initialize the `.env` file, and then you're good to go.

This is on version 3.9.2
