### ISSUE TITLE
feature request - Add ability to use environment variables for auth to AWS KMS

### ISSUE THREAD

**Issue by cmosetick** [mozilla/sops#432]
The README file says that `~/.aws/credentials` file must be used to authenticate to AWS KMS.  
I have ran a couple basic tests, and have indeed, found that to be true!

It would be wonderful if `sops` had the ability to use the standard AWS environment variables to authenticate to AWS KMS.
e.g.
```
AWS_ACCESS_KEY_ID=<key>
AWS_SECRET_ACCESS_KEY=<secret_key>
```

**Comment by autrilla** [comment]
Hmm, we use https://docs.aws.amazon.com/sdk-for-go/api/aws/session/ to authenticate to AWS, which if I'm reading correctly should look at those env vars.

**Comment by jvehent** [comment]
It does. Simply export them in your environment and use sops, it'll work.

**Comment by cmosetick** [comment]
I just re-ran my test scenario using environment variables, and it works correctly now. I'm not sure how I got the test case to fail the first time, but it's working now. Thanks again for the clarification.

I guess the README could use a minor update, but seems low priority.
>Your AWS credentials must be present in ~/.aws/credentials.

**Comment by jvehent** [comment]
Glad you got it to work :)

**Comment by CodingAnarchy** [comment]
Adding my 2 cents for a README update, as I also ran into this same confusion.
