### ISSUE TITLE
hostname in STS role session name may cause an error in the AssumeRole call

### ISSUE THREAD

**Issue by imsky** [mozilla/sops#441]
when assuming a role for KMS decryption, if a hostname contains characters that are not allowed by STS in a role session name, the operation will fail.

in code:
https://github.com/mozilla/sops/blob/a2d0328e35e6e37b51f3ad468dc6f213c7b44014/kms/keysource.go#L169

amazon reference:
https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html#options

this happened to us for a hostname with invalid characters in it, e.g. "hostname-(123)"

**Comment by ajvb** [comment]
@imsky I don't think we should allow for customization here, as it's yet another option and doesn't provide a lot of value.

But, this is totally absolutely a bug we should fix.

From the docs:
>The regex used to validate this parameter is a string of characters consisting of upper- and lower-case alphanumeric characters with no spaces. You can also include underscores or any of the following characters: =,.@-

I think that we should check that `hostname` conforms to that, and if not, strip out the characters that don't conform, e.g. `(` and  `)` in your example.

**Comment by ajvb** [comment]
Fixed in #558
