### ISSUE TITLE
Set up bors to allow running KMS integration tests on third-party pull requests

### ISSUE THREAD

**Issue by autrilla** [mozilla/sops#446]
We want to avoid third parties abusing our AWS credentials, even though they are restricted in what they're allowed to do. We'd still want to run the KMS functional tests against third-party pull requests, to verify they don't break anything before merging.

[Bors](https://bors.tech/) is a tool that can help with this. After a project member approves a PR, it merges it into a branch in the project, not in a fork, so when the tests run, they'd get the proper credentials injected. Plus we'd also get the benefit of solving the issue of multiple in-flight PRs that have no conflicts, but when merged, break the project.

**Comment by autrilla** [comment]
@jvehent anything against this? As far as I can tell bors is used heavily by Mozilla projects, so I imagine it's okay to use it here too.

**Comment by jvehent** [comment]
Philosophically, I'm not at all sold on the idea of delegating merge permissions to a bot ran by a third party. I think that's worse than only running acceptance tests on merges to master.

**Comment by ajvb** [comment]
@autrilla What do you think about setting up a `develop` branch (similar to what you'd have in [gitflow](https://nvie.com/posts/a-successful-git-branching-model/))? Then have all PR's merge into that branch before merging them into master?

**Comment by autrilla** [comment]
> @autrilla What do you think about setting up a `develop` branch (similar to what you'd have in [gitflow](https://nvie.com/posts/a-successful-git-branching-model/))? Then have all PR's merge into that branch before merging them into master?

We could certainly do that as well. It's basically what bors does. We lose by having to do it manually but win by not having a bot with commit access.

**Comment by ajvb** [comment]
> > @autrilla What do you think about setting up a `develop` branch (similar to what you'd have in [gitflow](https://nvie.com/posts/a-successful-git-branching-model/))? Then have all PR's merge into that branch before merging them into master?
> 
> We could certainly do that as well. It's basically what bors does. We lose by having to do it manually but win by not having a bot with commit access.

Yep. I think the only additional benefit (if we see it is a benefit) is that we could merge develop into master only when we cut a release, and therefore master == latest release.

**Comment by autrilla** [comment]
That's a very good point, actually. There's been several instances of people thinking a feature was released because the docs in master mentioned it, and people turn to github for docs.

**Comment by autrilla** [comment]
Closing since we aren't comfortable with the security model

**Comment by notriddle** [comment]
You could run your own instance of bors. The source code is all [right there](https://github.com/bors-ng/bors-ng).
