### ISSUE TITLE
Go Module Support

### ISSUE THREAD

**Issue by alee792** [mozilla/sops#447]
Go Modules don't officially land until Go 1.13, but it would be helpful to preemptively support it.

There is currently an issue when attempting to use SOPS/decrypt due to a dependency with `contrib.go.opencensus.io/exporter/ocagent`. The go toolchain will pull the most recent release, `v0.4.8`, but actually requires `v0.4.5`. 

Locking the dependency in a `go.mod` to `contrib.go.opencensus.io/exporter/ocagent v0.4.5 // indirect` solves this problem.

To be fair, this is an issue with Azure's package. However, it's a good opportunity to make the package work right out of the box.

**Comment by tariq1890** [comment]
+1 @autrilla @jvehent Your thoughts please.

**Comment by autrilla** [comment]
I don't have time (and I imagine Julien has even less 😉 ) to implement  this but as long as it doesn't break existing users, it'd be great to have this.

**Comment by tariq1890** [comment]
I can try taking some time out for this. I couldn't quite gather what `sops` is currently using for dependency management right now.

**Comment by autrilla** [comment]
It uses govend

**Comment by davidovich** [comment]
see also #540

**Comment by davidovich** [comment]
I think this can be closed by #566
