### ISSUE TITLE
Can't encrypt env file

### ISSUE THREAD

**Issue by vojtechmasa** [mozilla/sops#455]
I am not able to encrypt file in ENV format. Getting a strange error about parsing a timestamp.
```
$ cat hello.env 
hello=10

$ sops-3.2.0 -pgp 'REAL_PGP_FINGERPRINT' hello.env
parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```
Encrypting `yaml` file works just fine.

Using version 3.2.0

**Comment by vojtechmasa** [comment]
I tried a workaround - using "binary" encryption, but it doesn't work either:
```
$ sops-3.2.0 --input-type binary --pgp 'REAL_PGP_FINGERPRINT' hello.env
Error unmarshalling input json: invalid character 'h' looking for beginning of value
```

**Comment by autrilla** [comment]
You have to use `-e` to encrypt files. `sops` without any mode flag uses the editor mode, which requires the file to be encrypted already.

Try `sops-3.2.0 -pgp 'REAL_PGP_FINGERPRINT' -e hello.env`

**Comment by vojtechmasa** [comment]
Thanks a lot for the help. It works.
