### ISSUE TITLE
Feature request: enable generic 'unencrypt files; run process; re-encrypt files' workflow

### ISSUE THREAD

**Issue by jpluscplusm** [mozilla/sops#482]
Hi! Thanks or making `sops` - I'm finding it really useful :-)

Here's a use case which I'd love to be able to handle cleanly with the tool.

Often I have multiple encrypted files required by a single process. (In my case it's `bosh create-env` and the resulting `state.json` and `creds.yml`).

It would be fantastic to be able to run something like:

```
sops unlock-and-execute --exec ./script <file1> <file2> <file3>
```

... and have sops:

- unencrypt each file
- execute the `--exec` param
- re-encrypt each file **irrespective** of the script's exit code
- exit with the script's exit code

The benefit of doing this natively with sops, and not just a wrapper script, is the reassurance it can offer that files will *definitely* get re-encrypted afterwards. In other words, there's zero chance of the plaintext getting left around afterwards.

At the moment it's *just* about possible to fake this up with nested invocations of sops with a rather complex system of scripts and `EDITOR` overriding.

This setup, however, doesn't deal nicely with the underlying command exiting with a non-zero exit code, which I have to swallow in the calling script and pass back via the filesystem. 

Regardless of this, it's not a "nice" setup by any means!

Any thoughts on this feature? Would it be helpful to anyone else?

**Comment by autrilla** [comment]
This has been suggested before, at least internally at Mozilla, so you're not alone 😄 . I thought we already had an issue for this, but apparently not.

I am definitely not against this, but I have some comments:

> sops unlock-and-execute --exec ./script <file1> <file2> <file3>

This is nitpicking, but we'd need to tell sops what files to use, not just your script.

>  The benefit of doing this natively with sops, and not just a wrapper script, is the reassurance it can offer that files will definitely get re-encrypted afterwards. In other words, there's zero chance of the plaintext getting left around afterwards.

This is unfortunately kind of impossible. There is the possibility that e.g. the called script never exits (we could set up timeouts and such though). There is the possibility that we run out of memory when reencrypting, or the computer just halts or whatever. Functionality wise, it wouldn't be much different than a bash exit trap.

> At the moment it's just about possible to fake this up with nested invocations of sops with a rather complex system of scripts and EDITOR overriding.

Why do you need to override EDITOR?

Anyway, it seems this would indeed be helpful for other people, so it's probably better to support this natively rather than everyone developing their own set of scripts!

**Comment by jpluscplusm** [comment]
> This has been suggested before, at least internally at Mozilla, so you're not alone 😄 . I thought we already had an issue for this, but apparently not.
> 
> I am definitely not against this, but I have some comments:
> 
> > sops unlock-and-execute --exec ./script
> 
> This is nitpicking, but we'd need to tell sops what files to use, not just your script.

So I think there's a formatting issue here! In my original issue in the GH UI, the fake invocation looks like this:

`sops unlock-and-execute --exec ./script file1 file2 file3`, but with angle brackets around the file names. Those were my (not well thought out!) way of communicating which files need unencrypting :-)

Having thought about it a bit further, I think it _might_ make sense to break it down like this:

```
sops exec enc-file-1 enc-file-2 enc-file3 -- ./path/to/script script-param1 script-param2
```

I.e. using the common "`--` == no more params" convention to separate the sops-relevant args from the executed tool's args.

I **think** you'd want to avoid any `xargs -I{}` placeholder manipulation.  I also think you'd need to use a different mechanism from sops' standard editing route, which punts unencrypted files into a tempdir/tempfile, as the executed script might be relying on the contents of the rest of the directory in which it's running - which you couldn't easily make available in $TMP.

> > The benefit of doing this natively with sops, and not just a wrapper script, is the reassurance it can offer that files will definitely get re-encrypted afterwards. In other words, there's zero chance of the plaintext getting left around afterwards.
> 
> This is unfortunately kind of impossible. There is the possibility that e.g. the called script never exits (we could set up timeouts and such though). There is the possibility that we run out of memory when reencrypting, or the computer just halts or whatever. Functionality wise, it wouldn't be much different than a bash exit trap.

True.

I think at least one of your examples isn't sops' problem (timeout), as the principle of least surprise would let me run a command; let me forget that it's a command which prompts for a yes/no answer mid-run (e.g. Terraform), go to lunch, and not come back from lunch to see sops having killed the executed command. I think given non-pathological cases (your other 2 examples :-) ) it would be possible to offer a decent-*enough* commitment to not leaving unencrypted files on disk longer than the execution duration :-)

> > At the moment it's just about possible to fake this up with nested invocations of sops with a rather complex system of scripts and EDITOR overriding.
> 
> Why do you need to override EDITOR?

I was experimenting with overriding EDITOR to be my exec'd script, as above, and bastardising sops' "unencrypt; edit; encrypt" feature to implement a poor-man's version of this feature request.  As I said - it's not very nice!

> Anyway, it seems this would indeed be helpful for other people, so it's probably better to support this natively rather than everyone developing their own set of scripts!

I have an inkling this feature would find use in many folk's workflows :-) Thank you for considering it!

**Comment by jvehent** [comment]
I'm still skeptical. What format would sops use to pass data to the
executed scripts, and is that sufficiently differently from `sops -d |
scripts` to justify building it into sops?

**Comment by ancat** [comment]
I just opened a PR (#504) that may do what you're looking for, @jpluscplusm.

**Comment by jpluscplusm** [comment]
@ancat Many thanks! I'm only just back into a role where I need sops again, and it's fantastic to find this now available :-D Thanks so much for implementing and pushing it forward! 👏👏👏
