### ISSUE TITLE
Enable installing sops via Chocolatey

### ISSUE THREAD

**Issue by EricStG** [mozilla/sops#492]
Would it be possible to push sops releases to [Chocolatey](https://chocolatey.org/) (Windows package manager)?

**Comment by ajvb** [comment]
@EricStG Similiar to https://github.com/mozilla/sops/pull/450 - we as maintainers ship official binary releases to this repo's "Release" page, but we don't want to manage pushing to various nor do we want to recommend it as we do not have complete control over them.
