### ISSUE TITLE
Azure Keyvault key groups ignored?

### ISSUE THREAD

**Issue by Devin-Holland** [mozilla/sops#500]
Is there a reason in this block of code that there is a for loop for all types except Azure Keyvault? It just gets ignored. It does not seem like there is a way to encrypt using Azure Keyvault and another type within a group:

https://github.com/mozilla/sops/blob/a2d0328e35e6e37b51f3ad468dc6f213c7b44014/config/config.go#L161-L174

AzureKV is listed in the KeyGroups block but never used anywhere:

https://github.com/mozilla/sops/blob/a2d0328e35e6e37b51f3ad468dc6f213c7b44014/config/config.go#L66-L71

**Comment by autrilla** [comment]
I can't think of any reason. My guess is that the implementer of AzureKV forgot to add it there.

**Comment by Devin-Holland** [comment]
Opened PR #501

**Comment by autrilla** [comment]
Fixed in #502
