### ISSUE TITLE
[Question] Several encryption suffixes

### ISSUE THREAD

**Issue by naadev** [mozilla/sops#508]
Greetings...

I'm really glad to have discovered SOPS. It's really good stuff.

I'm working on a proposal to use SOPS as part of our standard security policies. In our case, I've found there could be, just to make it more transparent to final users that there are two suffix I'd like to see encrypted, in example all entries ending with:

- Password (i.e. ServicePassword)
- Key (i.e. ApiKey)

I'm wondering if there is any way to provide two suffixes when encrypting, I've tried with:

-  sops -e --output file.sops --encrypted-suffix Password --encrypted-suffix Key file.json
-  sops -e --output file.sops --encrypted-suffix Password,Key file.json
 
Is this a supported scenario somehow?

**Comment by autrilla** [comment]
That's not supported right now, but I guess we can turn this issue into a feature request for multiple encrypted/unencrypted suffixes :)

**Comment by jvehent** [comment]
Note for later, in case we decide to do this: don't use a regex or
interpreted string, since it could mess with the way people use it today,
but instead allow the flag to be set multiple times and turn it into an
[]string.

**Comment by bobmhong** [comment]
I just discovered the same limitation today and would like to see the ability to pass a list of encrypted suffixes.

**Comment by naadev** [comment]
I will try to spare some time today to provide a pull request to work with list... :)

Sent from my iPhone

On 20 Aug 2019, at 01:41, Bob Hong <notifications@github.com<mailto:notifications@github.com>> wrote:


I just discovered the same limitation today and would like to see the ability to pass a list of encrypted suffixes.

**Comment by autrilla** [comment]
I'm not sure multiple suffixes are worth implementing with #509 in the pipeline, as you can achieve the same behavior with both

**Comment by naadev** [comment]
That's what I was looking for... thank you @autrilla
