### ISSUE TITLE
`sops -e` should use creation rules for destination path, not source path

### ISSUE THREAD

**Issue by kiwicopple** [mozilla/sops#516]
## Problem

A command like `sops -e .env > ./secrets/dev.env` looks for creation rules matching `.env` (source) and not `./secrets/dev.env` (destination)

## Description

Let's say I have a `.sops.yaml` like this:

```yaml
creation_rules:
  - path_regex: .*/secrets/dev.* # destination path
    kms: 'AWS_KEY'
```

And I have a folder structure like this:

```sh
secrets/
.env
.sops.yaml
```

And then I call `sops -e .env > ./secrets/dev.env`

## Expected result

Sops should encrypt the file and save it in `secrets/dev.env`, and it should use the creation rules specified by the `path_regex: .*/secrets/dev.*` in `.sops.yaml`. This is useful for working with the `env` file in plain text editors, then encrypting them afterwards. There can't be a rule for the `.env` if in one computer it is supposed to be for staging, and on another it is supposed to be for dev.

## Actual result

I get the following error:

```
error loading config: no matching creation rules found
```

Hope that's clear, but happy to elaborate

**Comment by autrilla** [comment]
(from my phone, so please excuse brevity and typos)

Sops has no way to know that you’re writing the file to ./secrets/dev.env
as that’s handled by your shell.

**Comment by kiwicopple** [comment]
Aha of course. Thanks for the fast response @autrilla that makes sense. I will figure out a way using the rules/folder structures
