### ISSUE TITLE
Support for .env files

### ISSUE THREAD

**Issue by mdgreenwald** [mozilla/sops#517]
**Feature request**: Support for .env files would be nice to have as they are a common means of secret storage in development environments.

```env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=database_name
DB_USERNAME=root
DB_PASSWORD=password
```

Currently they are treated as binary files so they become a single line of encrypted data and you can no longer see individual keys.

**Comment by ajvb** [comment]
@mdgreenwald try adding `--input-type dotenv` to your encryption command. We do support `dotenv` format already.

**Comment by mdgreenwald** [comment]
Sorry about that!
