### ISSUE TITLE
Rewrite repository description

### ISSUE THREAD

**Issue by jsocol** [mozilla/sops#518]
Thanks for sops, it's really useful tool!

The current repo description—"or what happens when security guys write ops tools"—is not helpful and is unnecessarily gendered. It would be great if it actually described the tool, in a way that aligned with the COC.

**Comment by jvehent** [comment]
lol, I just changed this yesterday when I found an old quote from a coworker. It was meant to be funny, but I guess I'll change it back.

**Comment by jsocol** [comment]
Sorry, it sounded like you were going to change it but after closing the issue the description is still the same. I can't reopen this issue, either. Maybe the new(/old) description didn't save correctly?
