### ISSUE TITLE
programmatically encrypt a file

### ISSUE THREAD

**Issue by hoangelos** [mozilla/sops#529]
For use in Customize plugin, I have some Go Lang code that uses the decode API to decode SOPS encrypted files and deploy them as Kubernetes secrets.  These files we want to be created as a part of another library that's internal.  So we have a yaml object and want to be able to call a function and have it result in a sops encrypted file.  I don't see an encrypt API function like there is in the decrypt.

**Comment by ajvb** [comment]
You are going to want to take a look at the `encrypt` command code - https://github.com/mozilla/sops/blob/master/cmd/sops/encrypt.go#L57-L106

In particular, these lines:
https://github.com/mozilla/sops/blob/14a22d7a7060a0fba06c5dd716898d47728f0fce/cmd/sops/encrypt.go#L74-L99
