### ISSUE TITLE
Decrypt using sops on Gitlab Runner

### ISSUE THREAD

**Issue by ry1015** [mozilla/sops#534]
Hi,

As the title mentioned, is ti possible to decrypt a file using sops via Gitlab Runner? I'm trying to find a solution to enter the passphrase via a bash script.

Any suggestions is much appreciated.

Thanks,
Ry

**Comment by autrilla** [comment]
It should be no different than running on any linux machine. In the case of PGP, you can unlock the key beforehand. This is not really an issue with sops, so closing.
