### ISSUE TITLE
Allow encrypting/decrypting to output file named after original `secret.ext`/`secret.enc.ext` file

### ISSUE THREAD

**Issue by huguesalary** [mozilla/sops#535]
Imagine a folder currently containing thousands of sops [to be] encrypted files, in the form of: 
- `secret.env`
- `secret2.json` 
- `secret3.yaml`
- ...

I would like a feature that allows me to encrypt those file and automatically save the output to `secret.enc.env` or `secret2.enc.json` or `secret3.enc.yaml`.

I would also like the opposite feature, allowing me to decrypt `secret.enc.env` or `secret2.enc.json` or `secret3.enc.yaml` to `secret.env`, `secret2.json` and `secret3.yaml`.

For example:
- `sops --save-to-file --encrypt secret.env` 
  would create a new file `secret.enc.env`
- `sops --save-to-file --decrypt secret.enc.env`
    would create a new file `secret.env`

Is there a plan for such feature? If not, will a pull request for it be considered?

Thanks!

**Comment by ajvb** [comment]
@huguesalary In my opinion, what you are asking for can easily be accomplished with `bash` (or any other shell environment) and I don't see the need for a flag to replace core command line functionality.

If you are ok with `.enc` at the end, then something like this will work just fine:
```bash
$ for file in $(ls mydir/); do sops -e $file > ${file}.enc; done
```

If you want `enc` in the middle, then check out https://ss64.com/bash/tr.html
