### ISSUE TITLE
Tag releases with v prefix

### ISSUE THREAD

**Issue by carlpett** [mozilla/sops#540]
For importing sops as a Go module in other code, the release tags should be prefixed with a v, eg `v3.4.0` rather than `3.4.0`.

See https://github.com/golang/go/wiki/Modules#modules (emphasis mine):
>Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. **The leading v is required.** If using Git, tag released commits with their versions.

If this sounds acceptable, could you also add a v3.4.0 tag "on top" of 3.4.0?

**Comment by autrilla** [comment]
I pushed the v3.4.0 tag for now, and I guess we'll need to push an additional v tag every release, or stop pushing non-v tags.

**Comment by ajvb** [comment]
Thanks @autrilla - I can come back to this before the next release and update the travis config and such to support it.

**Comment by davidovich** [comment]
I believe this can be closed by #566
