### ISSUE TITLE
Unable to edit an unencrypted value without encryption key access

### ISSUE THREAD

**Issue by kanapuli** [mozilla/sops#546]
Hi, I have an sops encrypted file using AWS KMS key and the encrypted json (encrypted using --encrypted-regex 'password' option ) looks as follows, 

```
{
    "process_name": "thor",
    "password": "ENC[AES256_GCM,data:59shW6wFTIRYlCksQCc=,iv:QLyqE0gCUoNQQQyjeny8T3OblgGtUE=,tag:Ndk2qTaWc6cizQB11uk5Tw==,type:str]",
   "log_name": "/var/log/thor.log"
}
```

Now I dont have an AWS KMS access to decrypt the password field. But I want to edit the process name or other key-values. If I edit manually, file integrity is broken.  How can I edit the other encrypted values in the json without the KMS access ?  The whole idea keeping some keys unencrypted is that those values can be edited by anyone.

**Comment by jvehent** [comment]
You're going to have to slip the file in two, and only keep one encrypted with Sops.
The MAC protects the entire file regardless of encryption status. It's an integrity control, and bypassing it would open up a security hole.

The other option would be to edit modified files with `--ignore-mac` but, well, that's a bad idea.
