### ISSUE TITLE
Decryption fails on files encoded with anything other than UTF-8 (w/o BOM)

### ISSUE THREAD

**Issue by erick-thompson** [mozilla/sops#547]
I noticed that sops failed to decrypt any file that isn't UTF-8 without a BOM. UTF-8 with BOM fails, as does UCF-2 (any variant). I'm not sure if it's the library that is reading in the encrypted file, but it should handle standard encodings. 

The error is a variant of "Error unmarshalling input json: invalid character 'ÿ' looking for beginning of value", with the invalid character differing based on the particular encoding in the file.

**Comment by ajvb** [comment]
For JSON, UTF-8 is required by the spec (see https://tools.ietf.org/html/rfc7159#section-8.1)

**Comment by erick-thompson** [comment]
Thanks for the quick response. It seems like being more defensive about input would be useful, but I understand that it's in an underlying library.
