### ISSUE TITLE
SOPS doesn't map types when interpolating variables

### ISSUE THREAD

**Issue by OctavioCore** [mozilla/sops#570]
During my work, I've noticed that when either the variable inside the secrets file is either bool or int, there's an error occurring:

`err 8: failed processing release <release name hidden>l: helm exited with status 1:
  Error: render error in "<release name hidden>/templates/secret-application.yaml": template: <release name hidden>/templates/secret-application.yaml:14:40: executing "<release name hidden>/templates/secret-application.yaml" at <b64enc>: wrong type for value; expected string; got bool`

Values related are passed to Helm Charts like this: 
`APP_DEBUG: { {.Environment.Values.secrets.<release name hidden>.app.debug } }`

When the value was typed in `helmfile` like this:
`APP_DEBUG: "{ { .Environment.Values.secrets.<release name hidden>.app.debug } }"`
Everything works as intended.

**Comment by autrilla** [comment]
This is not an issue with SOPS, it's an issue with Helm. SOPS is correctly emitting values.

Either pipe it through `| quoted` (or whatever it's called), or consider not using a configuration system that works by templating YAML :).
