### ISSUE TITLE
Need updated aws-sdk-go for EKS IAM Role for Service Accounts

### ISSUE THREAD

**Issue by jessebye** [mozilla/sops#572]
Per https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html the minimum `aws-sdk-go` version to support the newer EKS IRSA feature (which allows pods to assume an IAM role with a Kubernetes Service Account) is `1.23.13`.

The current version in `go.mod` is `1.21.6`. Is there any reason we can't update to at least `1.23.13`? I don't think any breaking changes were introduced between those versions.

The primary use case for this is using SOPS inside a Kubernetes pod where it needs to assume the correct pod role. Newer versions of the `aws-sdk-go` support this natively, but the old version doesn't support it at all, thus making it impossible for us to properly use roles with SOPS in our Kubernetes cluster.

**Comment by autrilla** [comment]
There is no reason not to update. Do you want to submit a PR? I guess we can take PRs for dependency upgrades now that there's no more vendor/! It might require regenerating the mocks (`make mock` will do that).

**Comment by jessebye** [comment]
@autrilla I'd be glad to submit a PR. I'm getting stuck with tests failing though without making any changes:

```
--- FAIL: TestLoadConfigFileWithVaultDestinationRules (0.00s)
    config_test.go:326:
        	Error Trace:	config_test.go:326
        	Error:      	Not equal:
        	            	expected: "http://127.0.0.1:8200/v1/secret/data/foobar/barfoo"
        	            	actual  : "https://127.0.0.1:8200/v1/secret/data/foobar/barfoo"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-http://127.0.0.1:8200/v1/secret/data/foobar/barfoo
        	            	+https://127.0.0.1:8200/v1/secret/data/foobar/barfoo
        	Test:       	TestLoadConfigFileWithVaultDestinationRules
    config_test.go:330:
        	Error Trace:	config_test.go:330
        	Error:      	Not equal:
        	            	expected: "http://127.0.0.1:8200/v1/kv/barfoo/barfoo"
        	            	actual  : "https://127.0.0.1:8200/v1/kv/barfoo/barfoo"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-http://127.0.0.1:8200/v1/kv/barfoo/barfoo
        	            	+https://127.0.0.1:8200/v1/kv/barfoo/barfoo
        	Test:       	TestLoadConfigFileWithVaultDestinationRules
FAIL
coverage: 77.2% of statements
FAIL	go.mozilla.org/sops/v3/config	0.295s
FAIL
make: *** [test] Error 1
```

Any clues?

**Comment by autrilla** [comment]
@jessebye that's interesting. Did you update the Vault module as well? Although it looks to me like Vault hasn't updated it's default config for a while: https://github.com/hashicorp/vault/blame/ddf8c44e9c8a6fc24af13d749a1b6718d4c26f6d/api/client.go#L144

And the tests are passing on CI, so that's weird. I'll be able to test locally in a bit. Are you on Windows or a platform other than Linux or macOS?

**Comment by jessebye** [comment]
@autrilla I didn't do any update to the vault module, just pulled the repo and ran `make test`. I'm on a macOS machine.

**Comment by autrilla** [comment]
I managed to reproduce this as well. It really looks like the test is wrong and it should indeed be https, which makes me wonder why CI works. Interestingly we don't have any coverage data for the publish package...

I think you should change the test and submit a PR. I imagine CI should pass still, and we're just not running that test for some reason.
