### ISSUE TITLE
.deb package fails to install

### ISSUE THREAD

**Issue by jgmoss** [mozilla/sops#580]
.deb package fails to install with the following error:

> dpkg: error processing archive /home/jgmoss/Downloads/sops_v3.5.0_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'sops':
 error in 'Version' field string 'v3.5.0': version number does not start with digit

**Comment by dgsardina** [comment]
Exactly the same issue. Version for dpkg packages must start by digit as seen in [deb-version man pages](http://man7.org/linux/man-pages/man5/deb-version.5.html): 

> The upstream-version may contain only alphanumerics (“A-Za-
              z0-9”) and the characters . + - : ~ (full stop, plus, hyphen,
              colon, tilde) and should start with a digit.

**Comment by 0xClpz** [comment]
Same issue over here

**Comment by monotek** [comment]
Naming was changed from 3.4.0 to v3.5.0. 
Destroyed our Docker builds too.

**Comment by ajvb** [comment]
Working on a fix now.

**Comment by ajvb** [comment]
Not quite fixed. Will closed when the `.deb` has been fixed.

**Comment by ajvb** [comment]
The `.deb` attached to https://github.com/mozilla/sops/releases/tag/v3.5.0 should now work as expected.
