### ISSUE TITLE
unable to encrypt aws stack parameter files

### ISSUE THREAD

**Issue by tvddhi** [mozilla/sops#587]
aws stacks expecting the parameter file in json and in the following format:
```
[
  {
    "ParameterKey": "key1",
    "ParameterValue": "val1"
  },
  {
    "ParameterKey": "key2",
    "ParameterValue": "val2"
  }
]
```
if i want to encrypt this with sops, i got the following error:
```
Error unmarshalling file: Could not unmarshal input data: Expected JSON object key, got { of type json.Delim instead
```
Any ideas?

**Comment by autrilla** [comment]
This is documented

https://github.com/mozilla/sops#top-level-arrays

**Comment by tvddhi** [comment]
Thanks for your fast response!
As I can't modify the expected structure, I can't use it.. Is it planed in the next release(s)?

**Comment by autrilla** [comment]
I don't think we'll ever be able to do it. We need to put the SOPS metadata somewhere, and lists don't have an obvious place to do so. I guess we could put it in the end, or something like that.

As an alternative, you could use `--input-type binary` and `--output type binary`, but of course you lose some of the benefits of SOPS. Namely, you can't see the file structure when the file is encrypted.
