### ISSUE TITLE
sops exec-file filename

### ISSUE THREAD

**Issue by heydonovan** [mozilla/sops#601]
Currently, our script uses sops like so:

```
$ touch secrets.yaml.dec # for cases when secrets do not exist
$ sops --decrypt secrets.yaml > secrets.yaml.dec
$ ./program --input secrets.yaml.dec
```

We want to use the new `exec-file` feature to bypass the temp file. However, our script needs to know the name of the file beforehand, so we can create it if it does not exist. If sops tries to decrypt that blank file, it will throw the `sops metadata not found` error. Any workarounds?

**Comment by autrilla** [comment]
I don't understand what you want. What file name does your script need to know? I assume the name of the decrypted file as created by exec-file, which you can just get by doing something like `sops exec-file secrets.yaml './program --input {}'`

**Comment by heydonovan** [comment]
Was just trying to avoid additional logic checks on my side. Sometimes secrets.yaml doesn't exist, and so we create a blank file, since ./program will accept a blank file. Thanks though!
