### ISSUE TITLE
[KMS] Allow for endpoint

### ISSUE THREAD

**Issue by iMartyn** [mozilla/sops#605]
I'm currently looking at setting up an AWS-compatible KMS in my lab setup to allow for as-close-to-prod in an on-prem setup, and unfortunately you can't specify an endpoint in your `.aws/config` file ( https://github.com/aws/aws-cli/issues/1270 ) so it would need to be exposed in sops directly.

**Comment by autrilla** [comment]
I am initially opposed to doing this in sops. The AWS SDK should do it.

If anything, SOPS should have fewer knobs, not more.

**Comment by iMartyn** [comment]
Whilst I understand the position, the AWS SDK is never* going to do this.

It doesn't have to be a cli switch, could be an env variable, but short of crazy LD_PRELOAD magic, there's not going to be any way to set up a lab environment (or alternative to AWS/GCP once someone provides KMSaas) where you can use sops with remote KMS (GPG encrypted data in git is problematic for lots of reasons).

Note that this is exactly the same as all the apps that have s3-compatible storage, they have to allow for a different endpoint outside of the SDK.

* the linked bug has been open for 4 years with LOTS of people begging for this, it ain't happening.

**Comment by ajvb** [comment]
I'm with @autrilla on this. If the AWS SDK adds support, we can add support through it, otherwise no.

**Comment by iMartyn** [comment]
FWIW I've created a PR for this https://github.com/mozilla/sops/pull/608 so anyone coming across this issue can see what changes are needed to enable this as a flag.  Someone more familiar with the code could probably do it better, but it works for me.

My fork will be there for just this feature for now, I'll attempt to keep it up to date but no promises.
