### ISSUE TITLE
Remove temporary files, please.

### ISSUE THREAD

**Issue by xtrasolver** [mozilla/sops#624]
SOPS is very useful tool, but there is one issue preventing it to use in production. In does not delete temporary files.

sops --verbose test.enc.yaml

[PGP]    time="2020-02-07T17:58:34+01:00" level=info msg="Decryption succeeded" fingerprint=XXX...redacted....XXX
[SOPS]   time="2020-02-07T17:58:34+01:00" level=info msg="Data key recovered successfully"
[SOPS]   time="2020-02-07T17:58:34+01:00" level=debug msg="Decrypting tree"
[CMD]    time="2020-02-07T17:58:45+01:00" level=info msg="File written successfully"

It will left clear text file in temp folder e.g.:

C:\Users\Somebody\AppData\Local\Temp\433471151

sops -version
sops 3.5.0 (latest)

echo %EDITOR%
code --wait

systeminfo (redacted)
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

**Comment by dnicholas2001** [comment]
This is reproducible on Windows 10 and Git-Bash:

1. using default vim editor - if no changes, then the clear text file is not removed
1. using custom editor, EDITOR="atom -w", if no changes, the clear text file is not removed
1. Also, if there's a problem opening the editor, such as using sublime, the clear text file is not removed
1. However, if using vim or atom, if there's changes, then, the clear text file is removed

**Comment by ajvb** [comment]
Fixed with #685
