### ISSUE TITLE
sops exec-file does not propagate exit codes

### ISSUE THREAD

**Issue by starkpl** [mozilla/sops#626]
`sops exec-file` is a really cool feature, but I find it hard to use in CI pipelines because of one issue. Exit code of the executed command is not propagated, for example:
```bash
$ sops exec-file secret.enc.yaml 'exit 1'
$ echo $?
0
```

It would be great if the exit codes could be propagated or extracted somehow after running `sops exec-file` (and probably `exec-env` too).
Or maybe I am missing something?

**Comment by simonklb** [comment]
@ajvb When might we see a release that includes this fix? It's pretty critical in my case. Building from development works fine so would love to see this released asap. :)

**Comment by galindro** [comment]
me too

any return @ajvb ?

**Comment by 0anton** [comment]
I'm missing it too...

**Comment by simonklb** [comment]
@autrilla any chance you're able to cut a patch release with this fix? Or are you aiming for a specific milestone or release cycle?

**Comment by autrilla** [comment]
@simonklb I don't work for Mozilla anymore so I can't create releases. Maybe @ajvb or @jvehent have time to help.

**Comment by ni-binada** [comment]
Any updates on this? Would really like to have this working for exec-env.

**Comment by autrilla** [comment]
AJ mentioned they'd try and get a release done this month in another issue.
