### ISSUE TITLE
PGP decryption fails on Cygwin

### ISSUE THREAD

**Issue by bprager** [mozilla/sops#637]
It looks like I am having issues with the golang openpgp module:
```
$ echo "bar: foo" > test.yaml && sops --encrypt --in-place test.yaml && sops --decrypt test.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  0AA3952CF211E98ACD189E55BDA6C225628DB3CD: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Reading PGP message
      | failed: Could not establish connection with gpg-agent: dial
      | unix C:\Users\Berndpra/.gnupg/S.gpg-agent: connect: No
      | connection could be made because the target machine actively
      | refused it.; GPG binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.

$ sops --version
sops 3.5.0 (latest)

$ uname -a
CYGWIN_NT-10.0 HW-016990 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin

$ gpg --version
gpg (GnuPG) 1.4.23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 
Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by autrilla** [comment]
The GPG binary call is failing, so I would start by looking at why that’s
the case.

**Comment by bprager** [comment]
As you see from the command chain above, the encryption is working. The decryption fails.

**Comment by autrilla** [comment]
I can see that, but one of the reasons it's failing is because the call to
the GPG binary is failing. Without knowing why, it's hard to diagnose the
problem. I suggest you look at the GPG binary calls being made and execute
them manually to narrow it down.

**Comment by bprager** [comment]
Adrian, do you mean executing the GPG binary on the command line?

This seems to work fine:

$ echo "this is a test" | gpg --armor --symmetric --passphrase 1234 | 
gpg --decrypt --passphrase 1234
gpg: AES encrypted data
gpg: encrypted with 1 passphrase
this is a test

**Comment by bprager** [comment]
I solved it:
Apparently the issue is due to mixing Cygwin with Windows code.
Go is running within the Windows environment and expect GPG to be installed under Windows as well.
(It does not recognize the Cygwin GPG installation of course. Silly me.)
After installing GPG for Windows and adjusting %PATH% everything is now working as expected.
