### ISSUE TITLE
updatekeys subcommand behavior regarding path regex differs from edit command

### ISSUE THREAD

**Issue by yann-soubeyrand** [mozilla/sops#639]
Hi,

The behavior of the updatekeys subcommand differs from the edit command regarding path regex configured in .sops.yaml file. Indeed, when doing `sops secrets.yaml`, the regex is matched against the absolute path of secrets.yaml whereas when doing `sops updatekeys secrets.yaml` the regex is matched against the argument. If the argument isn't an absolute path, behavior is thus diverging.

**Comment by ajvb** [comment]
Fixed in https://github.com/mozilla/sops/pull/682
