### ISSUE TITLE
Support JSON arrays of arrays

### ISSUE THREAD

**Issue by nilium** [mozilla/sops#640]
Currently, JSON arrays of arrays cannot be parsed by sops, leading to an unmarshaling error. Given the following input, for example:

```json
{
	"ary": [[]]
}
```

sops will produce the following error:

```
[CMD]    ERRO[0094] Could not load tree, probably due to invalid syntax. Press a key to return to the editor, or Ctrl+C to exit.  error="Could not unmarshal input data: Expected JSON object key, got ] of type json.Delim instead"
```

The same input treated as YAML works, so the current workaround at least appears to be to use YAML.

**Comment by ajvb** [comment]
Fixsed with #642
