### ISSUE TITLE
Support keyservice in decrypt package

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#643]
I'm writing a tool that uses `sops` as a library via the `decrypt` package, and I would like to use that tool in a workspace with keygroups. Currently, `decrypt.File` does not make use of keyservices and thus decryption fails when more than one keygroup is required.

Is it just a matter of implementing https://github.com/mozilla/sops/blob/master/cmd/sops/decrypt.go#L22 in the decrypt package?

ni? @autrilla

**Comment by autrilla** [comment]
https://github.com/mozilla/sops/blob/4bc27f6eb72b1b4090753e9f3dba1d094544e1c3/decrypt/decrypt.go#L42

Is the line that should be using keyservices but isn't.

https://github.com/mozilla/sops/blob/4bc27f6eb72b1b4090753e9f3dba1d094544e1c3/sops.go#L604

And ^ would be the function to replace it with. I think this should be a new function in the public API of the `decrypt` package. I see two options here as well, with different tradeoffs:

- Take in a list of connection strings for the keyservices. This lets us not expose keyservice types to the world, so we can keep every package other than `decrypt` "private".
- Take in a list of `keyservice.KeyServiceClient`. Probably more flexible, but it forces us to expose that type.

FWIW, keygroups should work regardless of whether you use keyservices or not. I'm guessing you have some groups that can only be 'unlocked' by keys accessible through a keyservice and not locally.

**Comment by jvehent** [comment]
Thanks @autrilla !
I'm going through the code and got one question: using `sops` in a workspace, it seems to know somewhat magically that there's a socket in `/tmp/sops.sock`
```
$ sops --verbose -d foo.yaml 1>/dev/null
[CMD]	 INFO[0000] Connecting to key service                     address="unix:///tmp/sops.sock"
```
Yet I can't find any reference to sops.sock anywhere in the code of my local config. Do you remember how that gets discovered?

**Comment by jvehent** [comment]
Ah, nvm, @ajvb found it as a bash alias in the workspace.
