### ISSUE TITLE
Support Asymmetric encryption and Allow to edit the encrypted file with other editor

### ISSUE THREAD

**Issue by kumarsiva07** [mozilla/sops#648]
If you support Asymmetric encryption like ejson, then we don't need to provide the AWS KMS access for encryption. This will help the developer to encrypt without any production access. We can decrypt the data using the private which will be decrypted using the AWS KMS.
Also, It's difficult to edit the file always using the sops file.yaml. Instead of allowing to edit with any editor and encrypt command will encrypt the changed/added keys.

**Comment by heydonovan** [comment]
From the documentation:

```
Editing will happen in whatever $EDITOR is set to, or, if it's not set, in vim
```

**Comment by ajvb** [comment]
>If you support Asymmetric encryption like ejson, then we don't need to provide the AWS KMS access for encryption. This will help the developer to encrypt without any production access. We can decrypt the data using the private which will be decrypted using the AWS KMS.

I don't understand what this solves? What is the use-case here?

>Also, It's difficult to edit the file always using the sops file.yaml. Instead of allowing to edit with any editor and encrypt command will encrypt the changed/added keys.

As @heydonovan said, you just need to change the `EDITOR` env var. There are also plugins for editors like VSCode.

**Comment by autrilla** [comment]
I think @kumarsiva07 might mean the following:

Assume I have an encrypted file:

```
foo: ENC[some_aes_blob]
sops:
<sops metadata goes here>
```

I want to edit the file with my regular editor, and e.g. change it to the following:

```
foo: ENC[some_aes_blob]
bar: baz
sops:
<sops metadata goes here>
```

Then call `sops reencrypt myfile.yaml` and sops would figure out that the `bar` key needs to be encrypted. Likewise for editing or removing keys.

However, I don't think we should do this. You lose the benefits of MAC checking as soon as you do anything that is not adding a key. It would also make the code more complicated.

**Comment by kumarsiva07** [comment]
@autrilla  You understood my point. 

@ajvb - Developer's don't have the production cloud account access to their local machine. So developer could not encode the secret's and commit in git using symmetric. Asymmetric will help to encode the data without the any cloud provider using the public key.

**Comment by autrilla** [comment]
AWS KMS is asymmetric in practice due to the possibility of allowing only decryption through ACLs.

Perhaps using two keys, one to which developers have full access, and one with which they can only encrypt could work for you. Alternative you could have a CI pipeline with access to the development and the production key and have it reencrypt the file and push it to production machines.

**Comment by autrilla** [comment]
I'm closing this, since this can already be done with AWS's IAM and we are not going to support what I mentioned in https://github.com/mozilla/sops/issues/648#issuecomment-611668228.

**Comment by F21** [comment]
Apologies for resurrecting this closed issue, but has anyone found any workarounds or alternative tools for this? I am also looking for a way for developers to update / edit files without having access to the private key.

My use case is to store my encrypted secrets in git and have Terraform access them in Terraform Cloud. In my case, developers would have no reason to read any secrets, they should just be able to insert or update existing secrets and encrypt them with the private key. Using `age` gets us most of the way there as only Terraform Cloud should have access to the private key for decryption and the public key for encryption is included in the encrypted file. However, the need to decrypt everything before editing and encrypting means that developers will need access to the private key, which is something we don't need and want to avoid.
