### ISSUE TITLE
Lean ways to use SOPS in a CI/CD pipeline

### ISSUE THREAD

**Issue by Vad1mo** [mozilla/sops#656]
What are the recommended ways to use sops in a ci/cd pipeline. Without installing all the PGP or AWS/KMS tools?

I have been using git-crypt in the past, and there it is possible to export the Symmetric key and let the CI/CD inject the symmetric key to decrypt the secrets. 
So while on the DEV side PGP is used on the CI/CD side, it is the symmetric key.

**Comment by ajvb** [comment]
@Vad1mo If you want to use sops within a CI/CD pipeline, you are going to need to pass some sort of secret into the pipeline. There is not any tooling around exporting the symmetric key from sops, so you will need to utilize one of the key services, whether it is PGP, AWS KMS, GCP KMS, or Azure KMS.

What makes exporting the symmetric key preferable to passing in say AWS credentials to use AWS KMS?

**Comment by Vad1mo** [comment]
We have different scenarios for different clients and KMS isn't always possible. Ok, I guess PGP is going to be the easiest way.
