### ISSUE TITLE
Ambiguous wording on documentation regarding MAC

### ISSUE THREAD

**Issue by PastNullInfinity** [mozilla/sops#657]
Regarding [this paragaph](https://github.com/mozilla/sops#51message-authentication-code)(emphasis is mine):

> In addition to authenticating branches of the tree **using keys as additional data**, sops computes a MAC **on all the values** to ensure that no value has been added or removed fraudulently. The MAC is stored encrypted with AES_GCM and the data key under tree->`sops`->`mac`.

This makes it seem that the key _names_ are not used in the MAC  generation, which as far as I can tell is wrong, since trying to decrypt a SOPS file with some key name changed returns a `Error walking tree: Could not decrypt value: Could not decrypt with AES_GCM: cipher: message authentication failed`

I'd change this paragraph to make it clearer that the key/value pairs as a whole are used in the MAC generation, something like:

> In addition to authenticating branches of the tree using keys as additional data, sops computes a MAC on all **the key and value pairs** to ensure that no value has been added or removed fraudulently. The MAC is stored encrypted with AES_GCM and the data key under tree->`sops`->`mac`.

I did not delve too deep into the code to check the function, if I'm getting something wrong, please let me know

**Comment by autrilla** [comment]
The way it's worded is right AFAICT. Indeed, only the values are added to the MAC. The error you're seeing is because every value is encrypted with AES-GCM with the 'path' to the value as AAD. So while the MAC ensures the values are not tampered with by e.g. removing them entirely, the AES AAD ensures the values are not moved to a separate key.

**Comment by PastNullInfinity** [comment]
My bad, makes sense now that I think about it : )

Thanks for the clarification!
