### ISSUE TITLE
Parameter ---output not working as expected

### ISSUE THREAD

**Issue by sw360cab** [mozilla/sops#658]
Os: MacOs 10.14
Installation-type: Homebrew
Version: 3.5.0 (latest)

When I run:

`sops -e --kms="xxxxx:xxxxx" --aws-profile <my_aws_profile> privatekey.json --output-file privatekey_endc.json`

And

`sops -d privatekey_encd.json --output-file privatekey.json`

The output keeps on going on `stdout`

Note that the same does not happen, replacing option `--output` with UNIX redirect `>`, which works as expected.

Am I missing something?

**Comment by autrilla** [comment]
The flag name is --output, not --output-file.

**Comment by sw360cab** [comment]
I just made a wrong paste.
But is the same with --output.

`--outupt-file` was a guess to fix `--output` not working either.
@autrilla Does `--output` work for you?

**Comment by autrilla** [comment]
Works for me

```
/tmp
❯ cat foo.yaml
hello: world

/tmp
❯ sops --pgp 5096B537A412063B788BE2894546AB8A9EC6D8C9 --output foo.enc.yaml -e foo.yaml

/tmp
❯ head foo.enc.yaml
hello: ENC[AES256_GCM,data:pUE596s=,iv:7n0ITD2jJ3ejYj+MNnrIl6fdagKQTtyLNDtsZIreidw=,tag:Ur0cz42uMhtoA+eL77dk5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-22T15:53:30Z'
    mac: ENC[AES256_GCM,data:D5j6DhWaZ2S8B9g2knJ5Vf+Y8RMAMQEXewnXTzylY5lg3JY1DBSFZjrTHC1rjlOTwAwlKl5fNnwLUXLMqUb7rgbaz7/1t+PIZxuMwK5UlhQNVJcede9wiqt0reLneTLTKvIE+XimvHTFmyCw2Iwm7BgYUt451SUbzgDxZ7vkNG4=,iv:EmB3skBfTMtrVqVfvNmwZ2PlpDU1K64WEaqc8Dxkksw=,tag:NUtj2SW0mQDQCcsPNswEDQ==,type:str]
    pgp:
    -   created_at: '2020-04-22T15:53:29Z'
        enc: |

```

**Comment by sw360cab** [comment]
Ohhh, I see.
It is a matter of parameter positioning

This 2 works:
`sops --kms="xxxxx"  --output privatekey_enc.json -e privatekey.json`

`sops -e --kms="xxxxx"  --output privatekey_enc.json privatekey.json`

Mine version is not working:
`sops -e --kms="xxxxx" privatekey.json --output privatekey_end.json`

But in some way this make sense... In this case `--output` will be probably ignored because after input file.
