### ISSUE TITLE
Outdated IRC info in Readme

### ISSUE THREAD

**Issue by Kamahl19** [mozilla/sops#664]
There is an outdated contact info about mozilla IRC in README stating `Questions? ping "ulfr" and "autrilla" in #security on irc.mozilla.org (use a web client like mibbit ).`

 I tried to find you guys on mozilla Matrix however I couldnt find you there. Are there new contact information or can we remove it from README. I can provide a PR with new info or remove it

**Comment by autrilla** [comment]
I think for now it can probably be removed.

**Comment by Kamahl19** [comment]
Done :)
