### ISSUE TITLE
x509: certificate signed by unknown authority when running sops -v

### ISSUE THREAD

**Issue by sungcheng** [mozilla/sops#669]
sops 3.5.0
[warning] failed to retrieve latest version from upstream: Get https://raw.githubusercontent.com/mozilla/sops/master/version/version.go: x509: certificate signed by unknown authority

[warning] failed to compare current version with latest: Version string empty
 (latest)

**Comment by autrilla** [comment]
You're being MITMed. I suggest using a network that doesn't do that.

**Comment by sungcheng** [comment]
@autrilla, I am on my companies vpn so not sure how I am being MITMed, any suggestions on how to debug or bypass this issue?

**Comment by jvehent** [comment]
Your company VPN is routing your outbound HTTP traffic through a "web security" proxy that replaces the HTTPS certificate of github. But because Go/Sops does not know the local root used by the proxy, it throws an error (as it should).
