### ISSUE TITLE
`updatekeys` appears to ignore the config file switch

### ISSUE THREAD

**Issue by KayEss** [mozilla/sops#671]
Probably somewhere around this line needs to also check if the `--config` file switch was used and change accordingly https://github.com/mozilla/sops/blob/master/cmd/sops/main.go#L421

Our workaround is to rotate the key: `sops -i -r <file>` which does honour the `--config` switch.

**Comment by KayEss** [comment]
The workaround doesn't work :-( It just rotates the secret for the existing keys. Probably decrypting and re-encrypting (editing the file) will do it.

**Comment by ajvb** [comment]
Fixed with #672
