### ISSUE TITLE
dotenv format in 3.6 is incompatible with version 3.5

### ISSUE THREAD

**Issue by mltsy** [mozilla/sops#702]
After this change: https://github.com/mozilla/sops/pull/622

A dotenv file generated by 3.6.0 is not readable by SOPS 3.5 or earlier, because of the newly added single quotes around every value (which the old SOPS seems to be unable to parse).  I'm not sure whether this kind of change should be considered a breaking change or not, but given a typical use case (where you encrypt in one place and decrypt in another place), it's certainly not uncommon for one side to be using a different version than the other, so it's definitely pseudo-breaking.

One potential solution is to remember whether the file had quotes or not, and don't add quotes to a file that didn't have quotes (unless some flag is passed).  Another one might be a flag that can omit the dotenv quotes, like `--omit-dotenv-quotes` so that people running into this problem can at least generate a file in the old style without downgrading SOPS (it would be nice in this case if it were also a config setting in sops.yaml)

**Comment by autrilla** [comment]
Opened #706 to roll back that PR.

**Comment by jcassee** [comment]
Additionally, the 3.6.0 quoting behavior adds quotes _to the decrypted file_, even if no quotes were present initially. The .env file format is underspecified, and applications differ in opinion on whether quotes are quotes or just a part of the value. (See for example [dotenv-linter](https://github.com/dotenv-linter/dotenv-linter#quote-character).)

If something like #622 were reapplied, it would be nice to make sure the original quoting is conserved.

**Comment by DrPhil** [comment]
It's good that the bug is fixed, but it would be better if there was a new release with the bug fixed.

**Comment by mltsy** [comment]
I think the delays might have something to do with this recent announcement: https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/

Who knows what the future of SOPS looks like - I hope they still maintain it, or coordinate contributors to maintain it...

**Comment by farrellit** [comment]
the extra quotes mean 3.6 doesn't work with docker.  Why is there not a fix release for this yet?

**Comment by mltsy** [comment]
@farrellit see this comment by the primary maintainer: https://github.com/mozilla/sops/pull/706#issuecomment-677860526

@ajvb mentioned that he should be able to ship a release, potentially as soon as this week.

**Comment by ajvb** [comment]
Fixed with https://github.com/mozilla/sops/releases/tag/v3.6.1

**Comment by mltsy** [comment]
Wooo! Thanks 😄
