### ISSUE TITLE
Failing Make Install (wrong test inputs)

### ISSUE THREAD

**Issue by RishabhBhatnagar** [mozilla/sops#707]
`make install` is failing due to failing test of [sops/config/config_test.go](https://github.com/mozilla/sops/blob/master/config/config_test). Lines [375](https://github.com/mozilla/sops/blob/master/config/config_test.go#L375) and [379](https://github.com/mozilla/sops/blob/master/config/config_test.go#L379) of the [TestLoadConfigFileWithVaultDestinationRules](https://github.com/mozilla/sops/blob/5f7d32404639855ee4f35f187714d71fc43aa4fa/config/config_test.go#L371) are erroneous.

The test expects the output of `conf.Destination.Path` to have an `http` protocol but the function returns the output URL with `https` protocol which is causing the tests to fail.

**Comment by autrilla** [comment]
This has indeed been broken for ages :( #576 attempted to fix it. For now, you can set the VAULT_ADDR env var to http://127.0.0.1:8200 to solve it.

**Comment by RishabhBhatnagar** [comment]
Both the lines (375, 379) uses a config file with vault destination rules. If any URL is not specified, the `VaultDestination.Path` method of [publish/vault.go]() uses a base URL supplied by `getAddress()` method of *"github.com/hashicorp/vault/api"* library which returns a base address with protocol of `https`.

For a quick fix, I've updated the tests to use https instead of http.

**Comment by RishabhBhatnagar** [comment]
> 
> 
> This has indeed been broken for ages :( #576 attempted to fix it. For now, you can set the VAULT_ADDR env var to http://127.0.0.1:8200 to solve it.

As I can see that issue is associated with other things as well. Are we expecting that PR to be merged soon or should I create a new PR for fixing the current issue?

**Comment by autrilla** [comment]
I don't think that PR is going to be merged any time soon, so it would be great if you create a new PR for fixing the issue.

**Comment by ajvb** [comment]
Fixed with #731
