### ISSUE TITLE
sops fails to edit file when $EDITOR contains arguments

### ISSUE THREAD

**Issue by jbuck** [mozilla/sops#71]
My $EDITOR variable is currently set to `bbedit --wait --resume`. When I try to edit a file I get the following error:

```
Traceback (most recent call last):
  File "/Users/jbuckley/Library/Python/2.7/bin/sops", line 11, in <module>
    sys.exit(main())
  File "/Users/jbuckley/Library/Python/2.7/lib/python/site-packages/sops/__init__.py", line 298, in main
    run_editor(tmppath)
  File "/Users/jbuckley/Library/Python/2.7/lib/python/site-packages/sops/__init__.py", line 1282, in run_editor
    subprocess.call([editor, path])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Looking at the [documentation for subprocess.call](https://docs.python.org/2/library/subprocess.html#subprocess.call) this is occurring because `shell=False` by default. I can work around this by creating a shell script that runs the bbedit command with arguments but I wonder if this should be set to `shell=True`. It's recommended to [not do this with untrusted input](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments) so maybe it should actually remain False. Thoughts?

**Comment by jvehent** [comment]
I think `shell=True` may be fine given that it's only invoked in editing mode, in a shell created by the user. If someone can inject malicious parameters in that user's environment, there are worse things to do than messing with $EDITOR.

**Comment by claudijd** [comment]
Decent read here in stackoverflow that helped me catch up on the issue:
http://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess

@jbuck I would modify $EDITOR first to use a fully-qualified path first and and make sure you're running the latest version of bbedit.

@jvehent if @jbuck continues to have issues after those two are complete, you can probably modify the sops bin to extract and expand the path for the $EDITOR value and hopefuly avoid this bug.  If it's some weird internal thing in bbedit, maybe it can be reported upstream to see if they'd be willing to make a change.  I'd try all those options before shell=True, since it's likely people will wrap some automation code around this tool.

Another option you could try is make it configurable in sops with a warning about the implications and leave the default as shell=False.

**Comment by jbuck** [comment]
I tried with vim instead of bbedit to rule out something strange that it's doing:

```
(assume-aws-role prod)$ EDITOR='vim' sops common.yaml
INFO: assuming AWS role 'arn:aws:sts::361527076523:assumed-role/hiera-sops-prod/sops@jbuckley-23775'
INFO: temp file created at /var/folders/q2/vhg0j08n3fz3zsvph1rsw5080000gn/T/tmpRDS4a1.yaml
PANIC: common.yaml has not been modified, exit without writing
(assume-aws-role prod)$ EDITOR='vim -C' sops common.yaml
INFO: assuming AWS role 'arn:aws:sts::361527076523:assumed-role/hiera-sops-prod/sops@jbuckley-23775'
INFO: temp file created at /var/folders/q2/vhg0j08n3fz3zsvph1rsw5080000gn/T/tmp_tnTJ0.yaml
OSError: [Errno 2] No such file or directory
(assume-aws-role prod)$ EDITOR='vim ' sops common.yaml
INFO: assuming AWS role 'arn:aws:sts::361527076523:assumed-role/hiera-sops-prod/sops@jbuckley-23775'
INFO: temp file created at /var/folders/q2/vhg0j08n3fz3zsvph1rsw5080000gn/T/tmpdQLbuN.yaml
OSError: [Errno 2] No such file or directory
```

I had a look at the manpage for BBEdit and they explictly call out that some tools may not work correctly:

```
--resume (no short variant) Used in combination with -w or --wait, this switch
will cause the application which was frontmost when the bbedit tool was invoked
to be made frontmost again once you close the file(s) specified on the command
line.

  This is convenient if you are using the Terminal (or any third-party
  equivalent) to invoke a command which uses BBEdit as its editor (p4, cvs), and
  want to return back to the Terminal when the editing session is over.

    bbedit --wait --resume  ~/foo.txt

-w, --wait Wait until the file is closed in BBEdit. Normally, the bbedit tool
exits immediately after the file arguments are opened in BBEdit. This option
applies to both local files and files opened from FTP or SFTP servers.

  The -w option allows the bbedit tool to be used as an external editor for Unix
  tools that use the EDITOR global environment variable. To make this work using
  tcsh, add the following line to your .cshrc (or .tcshrc) file:

    setenv EDITOR "bbedit -w"

  Some tools (notably crontab), will not work correctly if your EDITOR variable
  consists of multiple terms. You can work around this by creating a simple
  shell script that calls bbedit -w, then using the shell script as your EDITOR.
  For example:

    #!/bin/sh
    bbedit -w "$@"
```

**Comment by gdestuynder** [comment]
without shell=True the env variables ($EDITOR) aren't automagically expanded and the path aren't automatogically expanded either ($PATH) - both are things that a shell will do for you.

Alternative is doing it by hand (os.path.expandvar and going through manually.. pain but might be what you want there), or using shell=True (which starts a shell really - sure its a little more dangerous and not very portable, though in some cases its totally ok, when you expect to use shell stuff, you gotta use a shell for example).

IIRC that's about it..

**Comment by jvehent** [comment]
Thank you gents. Let's see how far my patch takes us, and if people need more we can revisit.
