### ISSUE TITLE
Allow a YAML list under the gpg key in .sops.yaml

### ISSUE THREAD

**Issue by ajdergute** [mozilla/sops#713]
Currently it is not possible to add comments inside .sops.yaml configuration file. If doing so, sops complains about a missing double colon.

It would be nice to be able to insert such comments to clarify which key belongs to whom.

**Comment by autrilla** [comment]
They work perfectly fine for me. Can you share your .sops.yaml?

**Comment by ajdergute** [comment]
You're right. To clarify what I what, the following sample works for me:
`creation_rules:
  # a comment
    - pgp: >-
        85D77543B3D624B63CEA9E6DBC17301B491B3F21,
        FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
`

Whereas the following doesn't:

`creation_rules:
    - pgp: >-
        85D77543B3D624B63CEA9E6DBC17301B491B3F21, # a comment
        FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
`

I tried various combinations on lists but they do not work either.

**Comment by autrilla** [comment]
> Whereas the following doesn't:
> 
> ```
> creation_rules:
>     - pgp: >-
>         85D77543B3D624B63CEA9E6DBC17301B491B3F21, # a comment
>         FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
> ```

```
--- 
creation_rules: 
  - 
    pgp: "85D77543B3D624B63CEA9E6DBC17301B491B3F21, # a comment FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4"
```

Is what that YAML document means, so it makes sense that it doesn't work.

As for the other thing that doesn't work, it's simply because SOPS doesn't accept that format. We want the entry under "pgp" to be a comma-separated string of fingerprints, not a YAML list.

**Comment by ajdergute** [comment]
That's what I feare of. Thanks very much to clarify this.

It would be really nice to allow a YAML list under the gpg key.

**Comment by autrilla** [comment]
That would be kind of hard to do in a backwards compatible way AFAICT, but I would be happy to review a proposal for how to do it.

**Comment by ajdergute** [comment]
I'm think of the following:

If I'd use only one key group data should not be split up, but I should be able to use YAML lists.

Maybe this is a valid workaround for this. What do you think? Should I give it a try?

**Comment by ajdergute** [comment]
Using one key group with a YAML list works perfectly fine for me.
