### ISSUE TITLE
`sops -e data --output data.enc` doesn't output to ./data.enc as expected

### ISSUE THREAD

**Issue by colemickens** [mozilla/sops#716]

**Comment by colemickens** [comment]
So, #703 is painful, redirecting to a file seems perilous, so I looked at `sops --help` and noticed this:

```
   --output value                           Save the output after encryption or decryption to the file specified

```
however, it still just outpust to stdout?

**Comment by colemickens** [comment]
Am I misunderstanding the comment? The lack of tests to catch #703 (which can cause data loss) or this, is sort of concerning as someone very excited about, but new to `sops`.

**Comment by colemickens** [comment]
Oh. So `sops` is extremely dependent on the order of flags presented to it:

* `sops -e data --output data.enc --verbose` does not output to the file, and is not verbose
* `sops --verbose --output data.enc -e data` works:

```console
$ ls ./data.enc
ls: cannot access 'data.enc': No such file or directory

$ sops --verbose --output data.enc -e data
[PGP]	 INFO[0000] Encryption succeeded                          fingerprint=FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
[AZKV]	 INFO[0001] Encryption succeeded                          key=sops-key version=6e538f7c6d714d138226082070d1fe99

$ cat ./data.enc
{
	"data": "ENC[AES256_GCM,data:BDeAFA0gs+OC...
```

This is pretty painful.

**Comment by autrilla** [comment]
PRs welcome.

**Comment by colemickens** [comment]
Ack, big thanks for cross-linking issue, I really should've found that.

**Comment by colemickens** [comment]
@autrilla you don't have opinions about the replacement library, do you?

**Comment by autrilla** [comment]
Not really. This would be quite a painful change to make, I imagine. Our argument handling and design in general has not been great, mainly for wanting to maintain backwards compatibility with the Python version. Changing it while ensuring backward compatibility is going to be very hard, but I'm definitely willing to review proposals.

**Comment by colemickens** [comment]
>mainly for wanting to maintain backwards compatibility with the Python version. 

Aha! Thanks again for more details. And your work on `sops` and time looking at my Issues.

(Also, just in case someone might be given the wrong impression, I don't plan to look at this given this new information.)
