### ISSUE TITLE
not sure how to co-erce/predict type detection?

### ISSUE THREAD

**Issue by colemickens** [mozilla/sops#717]
```
> cat drone.env 
DRONE_SECRET=kajsdflkjadsdkfhakjdhfakljsdhf%

> sops --verbose --output drone.env.sops -e drone.env    

> sops --verbose --output drone.env -d drone.env.sops
Error unmarshalling input json: invalid character 's' looking for beginning of value
```

But if I specify the `--input-type binary --output-type binary`, then it does what I (think I) want it to do.

Is there a way that I can be naming files, or directing sops via `.sops.yml`, or I am misunderstanding something? I might have guessed that the "type" would be self-identifying in the sops encrypted payload?

**Comment by autrilla** [comment]
The file type (unless overriden) is based on the file extension of the input file. `drone.env.sops` has `.sops` as the extension, which sops will treat as an unknown type and default to our BINARY format (which is wrapped in JSON). Naming it `drone.sops.env` should work. We've seen people encounter similar issues in the past, and documented it on https://github.com/mozilla/sops#31yaml-and-json-type-extensions, kind of. But now with --output existing (it didn't back then), things become more confusing.

**Comment by autrilla** [comment]
As a note, you probably do not want `--input-type binary --output-type binary`. What you probably want is to either make the file end in `.env`, or  use `--input-type dotenv --output-type dotenv` in your decrypt call.

**Comment by colemickens** [comment]
Got it. Thanks for mentioning both options - I hadn't sticking the sops in the middle.
