### ISSUE TITLE
Force binary encryption?

### ISSUE THREAD

**Issue by alexgeek** [mozilla/sops#723]
I have a service account key (key.json) and if I encrypt it with `sops -e` it doesn't treat it as binary and changes the formatting. 
When I decrypt it later it's sha256sum doesn't match the original which can cause some issues with comparisons. 

Is there a flag to force sops into treating it as binary?

**Comment by jvehent** [comment]
You can either set the file extension to something that isn't associated with a supported format (eg. `.bin`), or you can use the `--input-type binary` flag.
