### ISSUE TITLE
Invalid deprecation warning about GPG key fetching?

### ISSUE THREAD

**Issue by Zebradil** [mozilla/sops#749]
I got the following deprecation messages while I was playing around with sops:

```
[PGP]    WARN[0003] Deprecation Warning: GPG key fetching from a keyserver witihin sops will be removed in a future version of sops. See https://github.com/mozilla/sops/issues/727 for more information.
[PGP]    WARN[0004] Deprecation Warning: GPG key fetching from a keyserver witihin sops will be removed in a future version of sops. See https://github.com/mozilla/sops/issues/727 for more information.
```

My `.sops.yaml` contains two GPG fingerprints to encrypt a file with.
The corresponding GPG keys are imported into my gpg keyring and I see them in the output of `gpg --fingerprint`.
I'm also sure that at least one of the two keys is not published on https://keys.openpgp.org (which is currently used by sops, if I'm not mistaken).

If I add a fingerprint of non-existing key (just some random fingerprint), I still see the deprecation warnings for all fingerprints from `.sops.yaml`, but now encryption fails with the following error:

```
error updating one or more master keys: [failed to encrypt new data key with master key "3F2540F5C7A2DD39030476CE3446FAE369C9A8B4": could not encrypt data key with PGP key: golang.org/x/crypto/openpgp error: key with fingerprint 3F2540F5C7A2DD39030476CE3446FAE369C9A8B4 is not available in keyring and could not be retrieved from keyserver; GPG binary error: exit status 2]
```

This error message shows that sops is actually getting at least one public key from my local keyring and does not require fetching the first two keys from a keyserver.

**Comment by uwehdaub** [comment]
We get this warning even not using a keyserver at all.

**Comment by Zebradil** [comment]
From [the code](https://github.com/mozilla/sops/blob/38b25bd449619e1d6da20e637702f7c73203aa44/pgp/keysource.go#L108-L124) I see that it should not request keyserver if the key is found in pubring. And while looking further I noticed that sops actually can't load pubring which is created by GnuPG (which I use on Linux currently).

```golang
func (key *MasterKey) pubRing() (openpgp.EntityList, error) {
	return key.loadRing(key.gpgHome() + "/pubring.gpg")
}
```
It tries to load `pubring.gpg`, but there is only `pubring.kbx`.

**Comment by ajvb** [comment]
This is due to the ordering of the PGP `Decrypt()` function:
https://github.com/mozilla/sops/blob/38b25bd449619e1d6da20e637702f7c73203aa44/pgp/keysource.go#L223-L238



---

The `key.decryptWithCryptoOpenpgp()` call is the one that is causing this deprecation warning to be logged as it is failing to find the key and then trying the keyserver. Then `key.decryptWithGPGBinary()` is called and succeeding.

**Comment by Zebradil** [comment]
Thanks for the explanation!
Do you think it makes sense to change the code to request keyserver only once? Or it doesn't make sense because the deprecation will be removed soon?

**Comment by ajvb** [comment]
> Thanks for the explanation!
> Do you think it makes sense to change the code to request keyserver only once? Or it doesn't make sense because the deprecation will be removed soon?

Yeah the latter, I think it would be best to leave it as we'll remove this code entirely in the next release.

**Comment by Zebradil** [comment]
Got it, thanks again.

**Comment by karlschriek** [comment]
Any update on this? I am still seeing this warning on v3.7.1
