### ISSUE TITLE
Sops does not preserve quotation marks

### ISSUE THREAD

**Issue by cslocum** [mozilla/sops#760]
I've got a YAML file that I've created using sops with KMS and an AWS role.  I'm able to open up the YAML file in my editor, populate it, and save.  But when I reopen the file with sops, all of the lines that had been in quotation marks have been stripped of the quotes.

I am using sops version 3.6.1.

I've searched online and have not seen any reports of this problem.  I have also used this version of sops on another ec2 instance, with the same setup, and I did not have this problem.  I'm sure I'm doing something wrong, but if anyone has any insight, I'd be very appreciative.  Thanks!

**Comment by autrilla** [comment]
Those are semantically identical. At this point, SOPS does not and does not intend to preserve style in YAML files.

**Comment by cslocum** [comment]
Thank you for your feedback!  I discovered that it was a different issue entirely.  The error message given was a bit misleading, but ultimately did help me find the issue (conflicting/duplicate YAML code in a secret versus non-secret file).

**Comment by blackrepo** [comment]
I am also seeing this behavior and am trying to use this to protect YAML files used by Puppet Hiera. Unfortunately, sops is removing double quotes on strings, which is breaking interpolation of variables. Any workarounds?

From Puppet's hiera documentation:
_In YAML files, any string containing an interpolation token must be quoted in order to comply with the YAML spec. (Under Ruby 1.8, interpolation tokens in unquoted strings will sometimes work anyway, but this can’t be relied on.)_

https://puppet.com/docs/hiera/1/variables.html

**Comment by felixfontein** [comment]
Can you provide an example where it actually breaks something?

**Comment by nateblack** [comment]
Thank you for your response. After further testing, it appears that I may have been incorrect and interpolation appears to be working even without quotes. I will continue to do further testing. Thanks again!

**Comment by maxdiebold-erg** [comment]
This does break cases where single quotes are intended to _prevent_ string interpolations. For example, when decrypting YAML secrets with the flag `--output-type dotenv` and one of the secret values is `'$password'`.

**Comment by felixfontein** [comment]
Did you try having quotes in the value? Having quotes in the YAML representation, where the resulting value doesn't have quotes, won't give you quotes when converting the format.

For example:
```yaml
password_1: "'$password'"
password_2: >-
  '$password'
```

**Comment by maxdiebold-erg** [comment]
@felixfontein That works! Thanks.
