### ISSUE TITLE
[Question] .sops.yaml creation_rule for Azure Key Vault

### ISSUE THREAD

**Issue by dkirrane** [mozilla/sops#768]
What is the `.sops.yaml` creation rule entry required for Azure Key Vault?
It doesn't seem to be documented.

I've tried the following without luck
```
# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *.dev.yaml,
        # Key Vault set A is used
        - path_regex: .yaml$
          azure_kv: 'https://sops-demo-12345.vault.azure.net/keys/sops-key/qqqqqqqqqqqqqqqqqqqqqasdasdas'
```

**Comment by colemickens** [comment]
Use `azure_keyvault`: https://github.com/mozilla/sops/blob/master/config/config.go#L72

**Comment by VanKosiara** [comment]
I had the same problem today.
I'd consider updating docs because `azure_kv` is mentioned everywhere instead of `azure_keyvault`.
