### ISSUE TITLE
decrypt file by passing private key as an command option

### ISSUE THREAD

**Issue by jjangga0214** [mozilla/sops#772]
Hi, I am using sops(v3.6.1) only with PGP (`gpg`(`v2.2.18`)).

```bash
sops --input-type dotenv --output-type dotenv -d .env.enc --output
```

When I try to decrypt a file, the command above shows me a GUI password alerts like this.

![Screenshot from 2020-11-18 23-46-29](https://user-images.githubusercontent.com/28584151/99545686-00af0e00-29f9-11eb-9f4f-8e8d23094524.png)

However, I want to decrypt only by CLI, to use sops in CI.

Would it be possible?

Thanks.

**Comment by autrilla** [comment]
Sure, just remove the passphrase from your GPG key, or use some other key type such as AWS KMS that does not require a passphrase. You'll still need proper credentials in your CI machine.

**Comment by jjangga0214** [comment]
@autrilla Thanks a lot!

For forks who may have same issue, I leave a [link]() about how to remove passphrase from private key.
