### ISSUE TITLE
SOPS errors out if the value of the EDITOR environment variable contains spaces.

### ISSUE THREAD

**Issue by akunaatrium** [mozilla/sops#778]
In Windows 10, using PowerShell 5.1 when setting the environment variable EDITOR as follows:

```pwsh
$env:EDITOR = 'C:\Program Files (x86)\Notepad++\notepad++.exe'
```

And trying to edit a file using sops like this:

`sops.exe .\file.enc.yaml`

The following error message is returned:

`Could not run editor: exec: "C:Program": file does not exist`

Expected behavior would be that the editor is opened up.

Is there any workaround or solution to this (didn't try a path without spaces and don't consider that as a viable workaround anyway).

**Comment by akunaatrium** [comment]
Discovered that one can use the legacy file name convention to describe file and folder names longer than 8 characters, like this:

```pwsh
$env:EDITOR = 'C:/Progra~2/Notepad++/notepad++.exe'
```

Notice the forward slashes as well. SOPS doesn't seem to support backslashes in the path.

**Comment by akunaatrium** [comment]
Notepad++ runs asynchronously by default, so basically if one chooses to use Notepad++ as the editor, as soon as sops opens up Notepad++, sops exits and says "File has not changed, exiting.". Just as a reference for people stumbling upon this problem, to make Notepad++ run synchronously, give the `-multiInst -nosession -notabbar` flags to the executable. Thus, setting the environment variable becomes:

```pwsh
$env:EDITOR = 'C:/Progra~2/Notepad++/notepad++.exe -multiInst -nosession -notabbar'
```

Haven't tried to set a permanent system wide environment variable yet but I suppose it works there as well.

**Comment by autrilla** [comment]
This is because we use shlex when parsing the $EDITOR:

https://github.com/mozilla/sops/blob/38b25bd449619e1d6da20e637702f7c73203aa44/cmd/sops/edit.go#L260

We have to way of knowing if the thing after the space is an argument or a path with a space. Have you tried quoting the path?

**Comment by akunaatrium** [comment]
Understandable. Good idea about the quotes, I'll try tomorrow.

**Comment by akunaatrium** [comment]
Or today. Looks like setting the path this way makes it work:

```pwsh
$env:EDITOR = "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -nosession -notabbar"
```

Case solved, thanks!

**Comment by patricknelson** [comment]
In case anyone wants an alternative, I discovered this worked with backslashes as well (this is the stored _unescaped_ value):

```
"C:\\Program Files\\Notepad++\\notepad++.exe"
```

What's odd is that it's already **in** the environment, so why is the extra escaping still needed?

![image](https://user-images.githubusercontent.com/4269377/102677528-bd5ed100-4157-11eb-9a45-dbdc07bd1945.png)

**Comment by parwejmetroag** [comment]
> ```powershell
> /notepad++.exe' -multiInst -nosession -notabbar"
> ```

Above worked for me....have to add correct notepad++ path. However, while saving the file, it keeps saying that file is opened in another program and doesn't allow to save. Any trick to solve this problem? @akunaatrium

**Comment by sarveswarreddy** [comment]
Add an env var with name EDITOR and use below value for Notepad++
`"C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -nosession -notabbar`
