### ISSUE TITLE
OpenPGP keys with passphrases

### ISSUE THREAD

**Issue by jimmycuadra** [mozilla/sops#78]
I'm trying to use sops in some automation where the PGP private key I'm using for decryption has a passphrase. The passphrase can't be entered interactively. Is there a way to supply a passphrase through sops? Glancing at the source code it looks like it just shells out to `gpg -d`, so this may not be possible right now. It looks like it'd need to explicitly accept a passphrase argument to pass on to GPG. If this isn't possible through sops right now, any ideas for workarounds? Thanks much.

**Comment by jvehent** [comment]
I would suggest using a gpg-agent and unlocking the passphrase prior to invoking sops. `gpg -d` will then talk to the agent and access the already unlocked private key.

**Comment by jimmycuadra** [comment]
Sounds reasonable. Thanks!
