### ISSUE TITLE
Attempting to edit an encrypted ENV file fails.

### ISSUE THREAD

**Issue by akunaatrium** [mozilla/sops#780]
Executing `sops configuration.enc.env` where `configuration.enc.env` is an encrypted ENV file results in the following error message:

```invalid dotenv input line:```

(And no editor is launched.)

Operating system: Windows 10
Shell: PowerShell 5.1
SOPS version: 3.6.1

**Comment by akunaatrium** [comment]
Trying with PowerShell Core (for both encrypting and editing) results in a different error:

```": extra text: 020-12-02T14:52:19Z```

The full line where this text is present looks like this:

```sops_azure_kv__list_0__map_created_at=2020-12-02T14:52:18Z```

**Comment by autrilla** [comment]
It seems like you might have some empty lines? I can't help you further without any steps to reproduce.

**Comment by akunaatrium** [comment]
Interesting, tried again now and now there is no error, editor opened up and all is well. I guess I did something wrong before, my bad.

**Comment by jesalves** [comment]
I'm having this error either on windows PowerShell or GitBash or Ubuntu terminal (WSL):

`": extra text: 021-12-10T16:49:40Z`

If anyone knows how to solve this, please let me know.

Thank you.

**Comment by andreassiegel** [comment]
@jesalves This seems to be a problem with the line endings of the file.

For ENV files, the line endings need to be set to Linux format (LF). You can configure that in your `.gitattributes` file:
```
# Ensure Linux line endings for env files
*.env text eol=lf
```
