### ISSUE TITLE
Decrypting a binary file fails.

### ISSUE THREAD

**Issue by akunaatrium** [mozilla/sops#781]
In PowerShell on Windows 10, encrypted a binary file using the following command:

```
sops.exe --encrypt --azure-kv $kv --input-type binary file.bin > file.enc.bin
```

Where `$kv` is the key identifier. Encryption works.

Trying to decrypt the `file.enc.bin` using the following command:

```
sops.exe --decrypt .\file.enc.bin > decrypted-file.bin
```

Results in the following error message:

```
Error unmarshalling input json: invalid character 'ÿ' looking for beginning of value
```

Just for the record, there is no `ÿ` character in the file.

**Comment by akunaatrium** [comment]
Looks like the problem comes from the fact that PowerShell uses an uncommon encoding when it writes the encrypted file to disk (UCS-2 LE BOM). Switching to PowerShell Core fixes the issue. I suppose if this encoding is not planned to be supported, the issue can be closed.

**Comment by ajvb** [comment]
Yeah, I'm not sure we want to support this within sops. Closing for now.
