### ISSUE TITLE
releases are in weird format

### ISSUE THREAD

**Issue by joe-getcouragenow** [mozilla/sops#785]
would be easier is like this:
https://github.com/google/ko/releases
https://github.com/google/ko/releases/tag/v0.6.2

make it much easier for tooling

at the moment the format sops uses is opaque.

**Comment by autrilla** [comment]
I don't see the difference between these two
```
https://github.com/mozilla/sops/releases/tag/v3.6.1
https://github.com/google/ko/releases/tag/v0.6.2
```

What do you mean?

**Comment by joe-getcouragenow** [comment]
hey @autrilla .
 
thanks for asking.

the difference is the file types that sops team for the binaries.

on mac, the darwin download is something thats not used much. windows is exe which is normal

but i was writing some toolng for users and sops and age and a few others were needs to be in the tooling download and SOPS is just not normal way compared to others.

others...

https://github.com/gohugoio/hugo/releases/tag/v0.79.0

https://github.com/goreleaser/goreleaser/releases/tag/v0.149.0

https://github.com/superfly/flyctl/releases/tag/v0.0.153

most use tar.gz, and then extracts to the OS's native binary.

**Comment by autrilla** [comment]
Sure, it's not a file type. Those are all executable binary files. Those _are_ already the OS's native binary. I don't see any benefit in wrapping this in an archive file, so I'm going to close this issue. I think it's easy to figure out that the file is a binary executable. Binaries in macOS and Linux do not have extensions, so it doesn't matter IMO.

If we were to rename it to sops-v3.6.1-darwin, is the extension now `1-darwin`? I don't think there's anything to fix here.

**Comment by joe-getcouragenow** [comment]
"sops-v3.6.1-darwin.tar.gz" is what i am suggesting. 

You know its for darwin and you know its compressed. so other tools that use reflection can make sense of it. 

Its machine readable and so able to be used in a toolchain.

**Comment by autrilla** [comment]
sops-v3.6.1-darwin is not a compressed file, it's an executable.

```
~/Downloads
❯ file sops-v3.6.1.darwin
sops-v3.6.1.darwin: Mach-O 64-bit executable x86_64
```

**Comment by joe-getcouragenow** [comment]
ok thankyou
