### ISSUE TITLE
SOPS has no way to mass decode to std out or local directories

### ISSUE THREAD

**Issue by kwsorensen** [mozilla/sops#790]
Use case:

Using sops to store Kubernetes secrets.
In a pipeline or deployment environment I would like to decrypt all the files of a certain format (such as *.enc.yaml) or even just all yaml files in a directory to then get applied to a Kubernetes cluster.

It seems that there is sops publish command, but no option to have it publish to std out or to local structures.

**Comment by autrilla** [comment]
We're unlikely to ever implement this because it's trivial to do with common UNIX utilities such as `find`.

**Comment by kwsorensen** [comment]
Is it a "we don't want it implemented" or a "we aren't going to do the work to implement it"? 

Because if you're open to the idea I could maybe take a look at implementing it and creating a PR.

**Comment by autrilla** [comment]
It's my opinion that SOPS has way too many features that make it harder to maintain and to use. I've had a hand in that by allowing and implementing some of those features. We have to support every feature we add forever, and that takes effort. For something like this that can IMO be done pretty easily with a very small script, I don't think it's worth it. Additionally, every small feature is something users have to read in our docs and command line flags.

If this is really something other people want, we can allow it. I hope you understand if we keep allowing in every feature any single person wants, things don't end up well. So this is a "we don't want it implemented", for now.
