### ISSUE TITLE
sops updatekeys is not subkey aware

### ISSUE THREAD

**Issue by abeluck** [mozilla/sops#808]
### Scenario

* a file is encrypted with sops to a PGP key and some other key (KMS or PGP doesn't matter, as long as it is available)
* the PGP key has an encryption subkey
* after some time the subkey expires
* a new encryption subkey is added to the PGP key

With the other key present, executing `sops updatekeys file.sops.yml` asserts that the file is "already up to date":
```
2021/01/27 17:56:41 Syncing keys for file /path/to/file.sops.yml
2021/01/27 17:56:41 File /path/to/file.sops.yml already up to date
```

As a workaround you can use `sops --rotate --in-place file.sops.yml`

This might be related to https://github.com/mozilla/sops/issues/511

**Comment by autrilla** [comment]
`sops updatekeys` is not designed to know when the underlying key changed (while keeping the same identifier), only to add/remove keys. If you don't change your `.sops.yaml`, SOPS won't know you want to change anything.

**Comment by abeluck** [comment]
> is not designed to know when the underlying key changed (while keeping the same identifier), only to add/remove keys. 

Understood! So `sops --rotate` is the proper solution for this usecase?

**Comment by autrilla** [comment]
That’s the best option right now, yes. I’m not quite sure how GPG subkeys
work, but I think you’d want to rotate the internal AES data key SOPS uses
anyway, so using rotate is best.
