### ISSUE TITLE
Can we have option of _encrypted

### ISSUE THREAD

**Issue by patiln** [mozilla/sops#81]
Is it possible to add feature where we can only encrypt part of file using _encrypted and rest of the files unencrypted.

same feature _unencrypted

**Comment by jvehent** [comment]
We could, but only if the default value is the empty string to make sure it is disabled by default.
If you're willing to write a patch for it based on the `_unencrypted` code, we can review it.

**Comment by autrilla** [comment]
Fixed in #323
