### ISSUE TITLE
Warn or Throw an Error when Opening a File that doesn't Match .sops.yaml

### ISSUE THREAD

**Issue by divy4** [mozilla/sops#824]
## Background

I work in an environment where ~100 people are using sops to encrypt files, with varying levels of access based on what collection of GPG keys each person has access to. With such a large number of people using sops, we've often run into scenarios like this:

#### Sops Version

`3.6.1`

#### .sops.yaml

```
creation_rules:
  - path_regex: secret.1$
    pgp: 'KEY_FINGERPRINT_1'
  - path_regex: secret.2$
    pgp: 'KEY_FINGERPRINT_2'
```

#### User A

- Has access to key pair for `KEY_FINGERPRINT_1`
- Does not have access to `KEY_FINGERPRINT_2`

#### User B

- Has access to both key pairs for `KEY_FINGERPRINT_1` and `KEY_FINGERPRINT_2`
- Has access to secret values that User A should not have access to

## Reproduction Steps

- From the root of the repo containing `.sops.yaml`:
  - User A creates `secret.1` by calling `sops secret.1` and editing the file as needed
  - User A copies `secret.1` to `secret.2`
  - User B opens `secret.2` by calling `sops secret.2`, adding values that User A should not have access to
  - User A can open `secret.2`, because `secret.2` is encrypted using the 'KEY_FINGERPRINT_1' key pair instead of `'KEY_FINGERPRINT_2`

## Requested Feature

To prevent the above scenario, please add a feature where sops will throw an error when it tries to open a file whose encryption options don't match the `creation_rules` in `.sops.yaml`. This could be similar to the MAC and the `--ignore-mac` flag, where sops would refuse to interact with a file unless an `--ignore-creation-rules` flag is passed.

**Comment by autrilla** [comment]
That's an interesting issue! I'm not sure we'd want to fix it this way, since creation_rules are, well, for creation of new files. Perhaps running some script that runs updatekeys and checks whether there's some changes as a pre-commit hook could work?

**Comment by divy4** [comment]
Sure, that's fair that the creation_rules should stay within their scope.

And I've actually already setup some automation on the server side that checks to make sure the keys are correct. But we're using Azure Repos as our git provider, which sadly doesn't support server-side hooks in favor of "build validation pipelines", which can't block pushes. And a large number of those ~100 people are fairly busy to the point that department-wide instructions like "please run this script to configure git hooks when cloning this repo" only have about a 70-90% retention rate for people that were present during the announcement and around 50% for new hires.

So, we've been able to make a significant reduction in occurrences, but they still happen every few months.

Perhaps even an `expected_encryption_rules` similar to the `creation_rules` or even an optional `expect_existing_to_match_creation_rules` boolean in the `.sops.yaml` could work?

P.s. I haven't contributed before, but I would be willing to try to implement this if we came up with a design that you agreed on.

**Comment by divy4** [comment]
@autrilla Any thoughts on this?

**Comment by autrilla** [comment]
The suggested implementation sounds good, but I don't think we'd want to merge a feature like this, since to my knowledge yours is the only organization that needs it. Since from the sound of it you'd need this to be in the "main" path of sops, it's an important increase in complexity. If it could be implemented as a subcommand, it wouldn't be as big a deal, but `updatekeys` kind of already does this as a subcommand.

**Comment by divy4** [comment]
Absolutely, I definitely understand wanting to keep feature bloat to a minimum. We can look into possibly maintaining a fork for us. But thank you very much for your time and the feedback @autrilla!
