### ISSUE TITLE
SOPS seems to add additional indentation when used with YAML literal block scalar

### ISSUE THREAD

**Issue by SiegfredRodriguez** [mozilla/sops#830]
SOPS 3.6.1
when using sops -p <mypgpkey> secrets.yaml, sops seems to add addition two space indentation, for example :

input data

```
data: |
  data1
  data2
  data3
```

output data after calling sops -d

```
data: |
    data1
    data2
    data3
```

**Comment by felixfontein** [comment]
sops serializes data with a YAML encoder; it doesn't make any promise on keeping formatting, it only promises that the resulting YAML file is equivalent to the original (which is the case in your example).
