### ISSUE TITLE
3.7.0 execuable is flagged as trojan by Microsoft (...and executables are also unsigned)

### ISSUE THREAD

**Issue by mmkonrad** [mozilla/sops#844]
Hello there,

I tried to install the current version 3.7.0 on my Windows machine...and got immediately warned by the Defender (and previously also by the Chrome Browser) that it contains a virus.

A check of the executable via [virustotal.com](https://www.virustotal.com/gui/file/0b9846636bbd43b4057cd9587a9e5fda98114e20c7177b142957390afa996a85/detection) reveals that Microsoft flagged it as a trojan.

**It is probably just a false positive, but please check what is going on there!**

Additionally, a fallback to the older 3.6.1 version is not suitable, due to the fact, that the executables are not signed...
Which makes it hard to install on machines that have a company policy that prevents the installation of unsigned executables....but I guess a certificate is not cheap?

Cheers,

Marcus

**Comment by AndrewSav** [comment]
Yep, also observing windows defender blocking it on Windows 10.

**Comment by ajvb** [comment]
@mmkonrad This may be due to our advisory for sops v3.7.0 and lower. Does v3.7.1 get flagged?

**Comment by AndrewSav** [comment]
3.7.1 seems to run fine here. Thanks.

**Comment by fetahokey** [comment]
> 3.7.1 seems to run fine here. Thanks.

https://www.virustotal.com/gui/file/a514bd0ade6d955a73f9c8b9dde6c33eca006430b0e72289467d2152c5321767/detection
