### ISSUE TITLE
Unable to decrypt dotenv files which has been transformed by git

### ISSUE THREAD

**Issue by solacens** [mozilla/sops#854]
When you develop in Windows machine, git will auto transformed the newlines from LF to CRLF for the file. After the transformation, the encrypted file won't be decryptable anymore. This issue somehow won't happen to other types of file, but **only dotenv**.

Step to reproduce:

1. Encrypt a dotenv file into new location encrypted
2. Encrypted dotenv is being transformed and committed
3. After git branch changes the file is being regenerated
4. Decrypt is now failed
5. After converting the newlines to LF in `code`, the file is decryptable again

**Comment by jaysonsantos** [comment]
@solacens this happens because before decrypting, sops will check the signature of the file. So, even if a single byte is changed, they cannot ensure that the content is safe do be decrypted, this is to avoid crypto attacks by manipulating the contents of an encrypted payload

**Comment by solacens** [comment]
Can be solved by `.gitattributes`.
