### ISSUE TITLE
Contributors communication

### ISSUE THREAD

**Issue by Moskovych** [mozilla/sops#886]
Regarding the page: [CONTRIBUTING.md](https://github.com/mozilla/sops/blob/master/CONTRIBUTING.md)

> ... contributors are on the #go channel on Mozilla's IRC server.

but regarding the https://wiki.mozilla.org/IRC

> As of March 2020, IRC.mozilla.org has been permanently decommissioned

Question is: Are there any channels, chats, where current and new contributors
can quickly communicate and discuss some implementation pieces, etc?

**Comment by autrilla** [comment]
Using GitHub discussions for this might work.

**Comment by Moskovych** [comment]
@autrilla , that's would be nice, but I see only one discussion there, hope it will change soon.

**Comment by ajvb** [comment]
Hey all, an update on this was just posted here: https://github.com/mozilla/sops/discussions/927#discussioncomment-2183834

We'll have more soon!

I'm going to close this out, but if you have any follow-up questions please post them to the thread linked above.
