### ISSUE TITLE
simple path regex not accepted

### ISSUE THREAD

**Issue by Morriz** [mozilla/sops#890]
Hi, I would expect this to work for a path_regex:

`^secrets.*.yaml$`

But I get errors that it won't find any matching rules that way. Now if I omit the `^` it passes, but also greedily tries to operate on unintended filenames, such as `blasecrets.asdf.yaml`.

Why is there no regex start delimiter usable? And until we get that working, what could be a workaround to make sure only filenames starting with `secrets.` will match?

**Comment by ede-n** [comment]
Could you try `'^(secrets.*\.yaml)$'`?

**Comment by Morriz** [comment]
Aha, thanks for pointing that out! Really helpful :)
