### ISSUE TITLE
descrypted data is different from before Encrypted if the dada is long number

### ISSUE THREAD

**Issue by liu9jian** [mozilla/sops#928]
![image](https://user-images.githubusercontent.com/9945339/131639598-2a7165c9-fb50-4051-8713-9f94f93d5a84.png)

encrypt:
![image](https://user-images.githubusercontent.com/9945339/131639781-e543d5fa-e21c-4235-89a5-01cb4ff7e561.png)

but it changed after decrypt
![image](https://user-images.githubusercontent.com/9945339/131639927-533759ff-cd47-4c2e-9f3c-24987a8757f0.png)

**Comment by felixfontein** [comment]
While Go does seem to have arbitrary precision support for integers (https://pkg.go.dev/math/big), I'm not sure yaml.v3 has support for that (that's the YAML parser and serializer sops is using).

As a workaround, you should probably store this as a string and not as an integer.

**Comment by liu9jian** [comment]
> While Go does seem to have arbitrary precision support for integers (https://pkg.go.dev/math/big), I'm not sure yaml.v3 has support for that (that's the YAML parser and serializer sops is using).
> 
> As a workaround, you should probably store this as a string and not as an integer.

Thanks

The yaml file will automatically recognize str. If you use quotation marks, it is equivalent to encrypting the quotation marks, but so far, the solution can only be quotation marks.
