### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by woodcockjosh** [mozilla/sops#941]
Just wondering if this project is being maintained since there hasn't been a release in 7 months.

**Comment by felixfontein** [comment]
It's definitely not dead. It's not very alive either, though, see #927.

**Comment by mitar** [comment]
Also, development happens in `develop` branch.

**Comment by hoonetorg** [comment]
Hi, the last commit in the develop branch is from July 21 2021.
Developers say: Not enough time.
#927 [@mhoye](https://github.com/mhoye) says, he will look into current sponsorship status.
The question is still valid. **Is this project alive?** Does Mozilla have another strategy for managing secrets in future.
Could somebody clarify the status here?
@autrilla @ajvb, anybody?

**Comment by ajvb** [comment]
Hey all, an update on this was just posted here: https://github.com/mozilla/sops/discussions/927#discussioncomment-2183834

We'll have more soon!

I'm going to close this out, but if you have any follow-up questions please post them to the thread linked above.
