### ISSUE TITLE
findKey(keysources []sops.KeySource) should be a method on sops.KeySource

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#97]
Users of the library currently need to reimplement `findKey` in their own code. Making it part of the `sops` package as a method of KeySource would avoid this.

**Comment by autrilla** [comment]
How about as a method of `Metadata`, so the user of the library doesn't have to iterate over all `KeySource`s?

**Comment by jvehent** [comment]
Works for me 👍

**Comment by autrilla** [comment]
Fixed in dd77627
