### ISSUE TITLE
export common errors from the sops package

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#98]
In userplex, I had to define a few custom errors that I think would be better placed in the sops package:
```go
const (
	errNotSopsFormat string = "sops metadata not found in input data"
	errInvalidMac    string = "failed to verify the integrity of the sops file (MAC mismatch)"
)
```
Maybe we need to rethink the error codes from the sops cmd line and export an error type that has both the error string and the code, similar to [os.PathError](https://golang.org/pkg/os/#PathError).

**Comment by autrilla** [comment]
MacMismatch can be found here: https://github.com/mozilla/sops/blob/go-sops/sops.go#L22

I am reluctant to exporting CLI exit codes, and in any case I think it should be the sops package that exports errors, not sops/cmd/sops. I'll expose the sops metadata missing error there too.

**Comment by jvehent** [comment]
> I am reluctant to exporting CLI exit codes

I can agree with that

> it should be the sops package that exports errors, not sops/cmd/sops

Yes, that's what I meant. Sorry if it wasn't clear.

**Comment by autrilla** [comment]
2437827 adds an error for when the sops branch is not found.
